= nn_allocmsg(3compat)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nn_allocmsg - allocate message (compatible API)

== SYNOPSIS

[source,c]
----
#include <nanomsg/nn.h>

void *nn_allocmsg(size_t size, int type);
----

== DESCRIPTION

The `nn_allocmsg()` allocates a message structure of size _size_, and is
primarily used to support zero-copy send operations, making use of the
`NNG_MSG` special size indicator.
The value returned is a pointer to the start of the message payload buffer.

The value of _size_ must be positive, and small enough to hold reasonable
message data plus book-keeping information.

NOTE: This function is provided for API
<<nng_compat.3compat#,compatibility>> with legacy _libnanomsg_.
Consider using the relevant <<libnng.3#,modern API>> instead.

The value of _type_ *must* be zero.
(This argument was reserved to support different kinds of memory spaces
for RDMA devices, but this was never developed in the legacy API.)

The returned message must be disposed of by either
`<<nn_freemsg.3compat#,nn_freemsg()>>` or
`<<nn_send.3compat#,nn_send()>>` when the caller is finished with it.

== RETURN VALUES

This function returns a pointer to message buffer space, or `NULL`
on failure.

== ERRORS

[horizontal]
`ENOMEM`:: Insufficient memory is available.
`EINVAL`:: An invalid _size_ or _type_ was specified.
`ETERM`:: The library is shutting down.

== SEE ALSO

[.text-left]
<<nn_errno.3compat#,nn_errno(3compat)>>,
<<nn_freemsg.3compat#,nn_freemsg(3compat)>>,
<<nn_reallocmsg.3compat#,nn_reallocmsg(3compat)>>,
<<nn_send.3compat#,nn_send(3compat)>>,
<<nng_compat.3compat#,nng_compat(3compat)>>,
<<nng.7#,nng(7)>>
