= nn_close(3compat)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nn_close - close socket (compatible API)

== SYNOPSIS

[source,c]
----
#include <nanomsg/nn.h>

int nn_close(int sock);
----

== DESCRIPTION

The `nn_close()` function closes the socket _sock_.
Any operations that are currently in progress will be terminated, and will
fail with error `EBADF`.

NOTE: This function is provided for API
<<nng_compat.3compat#,compatibility>> with legacy _libnanomsg_.
Consider using the relevant <<libnng.3#,modern API>> instead.

== RETURN VALUES

This function returns zero on success, and -1 on failure.

== ERRORS

[horizontal]
`EBADF`:: The socket is not open.
`ETERM`:: The library is shutting down.

== SEE ALSO

[.text-left]
<<nn_errno.3compat#,nn_errno(3compat)>>,
<<nn_socket.3compat#,nn_socket(3compat)>>,
<<nng_compat.3compat#,nng_compat(3compat)>>,
<<nng.7#,nng(7)>>
