= nn_errno(3compat)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nn_errno - return most recent error (compatible API)

== SYNOPSIS

[source,c]
----
#include <nanomsg/nn.h>

int nn_errno(void);
----

== DESCRIPTION

The `nn_errno()` function returns the error number corresponding to the
most recent failed operation by the calling thread.

NOTE: This function is provided for API
xref:nng_compat.3compat.adoc[compatibility] with legacy _libnanomsg_.
Consider using the relevant xref:libnng.3.adoc[modern API] instead.

IMPORTANT: The error numbers returned from this function may include
errors caused by system functions, which overlap the usual `errno` variable,
and this function simply returns the value of `errno`.
However, the values returned may include numeric values that are not
defined by the system, but are unique to _libnanomsg_, such as `EFSM`.

This library implements the following error numbers, in addition to any others
that might be set for `errno` by the underlying system:


== RETURN VALUES

This function returns the value of `errno`.
If no operation has failed, then this will be zero.

== ERRORS

[horizontal]
`EINTR`:: Operation interrupted.
`ENOMEM`:: Insufficient memory.
`EINVAL`:: Invalid argument.
`EBUSY`:: Resource is busy.
`ETIMEDOUT`:: Operation timed out.
`ECONNREFUSED`:: Connection refused by peer.
`EBADF`:: Invalid or closed socket.
`EAGAIN`:: Operation would block.
`ENOTSUP`:: Protocol or option not supported.
`EADDRINUSE`:: Requested address is already in use.
`EFSM`:: Protocol state incorrect.
`EPROTO`:: Protocol error.
`EHOSTUNREACH`:: Remote peer is unreachable.
`EADDRNOTAVAIL`:: Requested address is not available.
`EACCES`:: Permission denied.
`EMSGSIZE`:: Message is too large.
`ECONNABORTED`:: Connection attempt aborted.
`ECONNRESET`:: Connection reset by peer.
`EEXIST`:: Resource already exists.
`EMFILE`:: Too many open files.
`ENOSPC`:: Insufficient persistent storage.

== SEE ALSO

[.text-left]
xref:nn_strerror.3compat.adoc[nn_strerror(3compat)],
xref:nng_compat.3compat.adoc[nng_compat(3compat)],
xref:nng.7.adoc[nng(7)]
