= nn_recv(3compat)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nn_send - receive data (compatible API)

== SYNOPSIS

[source, c]
----
#include <nanomsg/nn.h>

int nn_recv(int sock, void *data, size_t size, int flags)
----

== DESCRIPTION

The `nn_recv()` function receives a message from the socket _sock_.
The message body must fit within _size_ bytes, and will be stored
at the location specified by _data_, unless _size_ is the
special value `NN_MSG`, indicating a zero-copy operation.

NOTE: This function is provided for API
<<nng_compat.3compat#,compatibility>> with legacy _libnanomsg_.
Consider using the relevant <<libnng.3#,modern API>> instead.

If _size_ has the special value `NN_MSG`, then a zero-copy operation
is performed.
In this case, instead of copying the message data into the address
specified by _data_, a new message large enough to hold the message data
will be allocated (as if by the
function `<<nn_allocmsg.3compat#,nn_allocmsg()>>`), and the message
payload will be stored accordingly.
In this case, the value stored at _data_ will not be message data,
but a pointer to the message itself.
In this case, on success, the caller shall take responsibility for
the final disposition of the message (such as by sending it to
another peer using `<<nn_send.3compat#,nn_send()>>`) or
`<<nn_freemsg.3compat#,nn_freemsg()>>`.

The _flags_ field may contain the special flag `NN_DONTWAIT`.
In this case, if the no message is available for immediate receipt,
the operation shall not block, but instead will fail with the error `EAGAIN`.

== RETURN VALUES

This function returns the number of bytes sent on success, and -1 on error.

== ERRORS

[horizontal]
`EAGAIN`:: The operation would block.
`EBADF`:: The socket _sock_ is not open.
`EFSM`:: The socket cannot receive in this state.
`ENOTSUP`:: This protocol cannot receive.
`ETIMEDOUT`:: Operation timed out.

== SEE ALSO

[.text-left]
<<nn_errno.3compat#,nn_errno(3compat)>>,
<<nn_recvmsg.3compat#,nn_recvmsg(3compat)>>,
<<nn_send.3compat#,nn_send(3compat)>>,
<<nn_socket.3compat#,nn_socket(3compat)>>,
<<nng_compat.3compat#,nn_compat(3compat)>>,
<<nng.7#,nng(7)>>
