= nn_recvmsg(3compat)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nn_recvmsg - receive message (compatible API)

== SYNOPSIS

[source, c]
----
#include <nanomsg/nn.h>

int nn_recvmsg(int sock, struct nn_msghdr *hdr, int flags);
----

== DESCRIPTION

The `nn_recvmsg()` function receives a message into the header described by
_hdr_ using the socket _sock_.

NOTE: This function is provided for API
xref:nng_compat.3compat.adoc[compatibility] with legacy _libnanomsg_.
Consider using the relevant xref:libnng.3.adoc[modern API] instead.

The _flags_ field may contain the special flag `NN_DONTWAIT`.
In this case, if no message is ready for receiving on _sock_,
the operation shall not block, but instead will fail with the error `EAGAIN`.

The _hdr_ points to a structure of type `struct nn_msghdr`, which has the
following definition:

[source, c]
----
struct nn_iovec {
    void * iov_base;
    size_t iov_len;
};

struct nn_msghdr {
    struct nn_iovec *msg_iov;
    int              msg_iovlen;
    void *           msg_control;
    size_t           msg_controllen;
};
----

The `msg_iov` is an array of scatter items, permitting the message
to be spread into different memory blocks.
There are `msg_iovlen` elements in this array, each of which
has the base address (`iov_base`) and length (`iov_len`) indicated.

The last member of this array may have the `iov_len` field set to `NN_MSG`,
in which case the function shall allocate a message buffer, and store the
pointer to it at the address indicated by `iov_base`.
This can help save an extra copy operation.
The buffer should be deallocated by xref:nn_freemsg.3compat.adoc[`nn_freemsg()`]
or similar when it is no longer needed.

The values of `msg_control` and `msg_controllen` describe a buffer
of ancillary data associated with the message.
This is currently only useful to obtain the message headers
used with xref:nng.7.adoc#raw_mode[raw mode] sockets.
In all other circumstances these fields should be zero.
Details about this structure are covered in
xref:nn_cmsg.3compat.adoc[`nn_cmsg(3compat)`].

== RETURN VALUES

This function returns the number of bytes received on success, and -1 on error.

== ERRORS

[horizontal]
`EAGAIN`:: The operation would block.
`EBADF`:: The socket _sock_ is not open.
`EFSM`:: The socket cannot receive in this state.
`EINVAL`:: The _hdr_ is invalid.
`ENOTSUP`:: This protocol cannot receive.
`ETIMEDOUT`:: Operation timed out.

== SEE ALSO

[.text-left]
xref:nn_cmsg.3compat.adoc[nn_cmsg(3compat)],
xref:nn_errno.3compat.adoc[nn_errno(3compat)],
xref:nn_recv.3compat.adoc[nn_recv(3compat)],
xref:nn_send.3compat.adoc[nn_send(3compat)],
xref:nn_socket.3compat.adoc[nn_socket(3compat)],
xref:nng_compat.3compat.adoc[nn_compat(3compat)],
xref:nng.7.adoc[nng(7)]
