= nn_socket(3compat)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nn_socket - create socket (compatible API)

== SYNOPSIS

[source,c]
----
#include <nanomsg/nn.h>

int nn_socket(int af, int proto);
----

== DESCRIPTION

The `nn_socket()` function creates socket using the address family _af_ and
protocol _proto_ and returns it.

NOTE: This function is provided for API
xref:nng_compat.3compat.adoc[compatibility] with legacy _libnanomsg_.
Consider using the relevant xref:libnng.3.adoc[modern API] instead.

IMPORTANT: Mixing the compatibility API and the modern API is not supported
on a given socket.

NOTE: Some protocols, transports, and features are only available in the modern API.

The address family _af_ can be one of two values:

[horizontal]
`AF_SP`:: Normal socket.
`AF_SP_RAW`:: xref:nng.7.adoc#raw_mode["`Raw mode`"] socket.

The protocol indicates the protocol to be used when creating the socket.
The following protocols are defined:

[horizontal]
`NN_PAIR`:: xref:nng_pair.7.adoc[Pair] protocol.
`NN_PUB`:: xref:nng_pub.7.adoc[Publisher] protocol.
`NN_SUB`:: xref:nng_sub.7.adoc[Subscriber] protocol.
`NN_REQ`:: xref:nng_req.7.adoc[Requestor] protocol.
`NN_REP`:: xref:nng_rep.7.adoc[Replier] protocol.
`NN_PUSH`:: xref:nng_push.7.adoc[Push] protocol.
`NN_PULL`:: xref:nng_pull.7.adoc[Pull] protocol.
`NN_SURVEYOR`:: xref:nng_surveyor.7.adoc[Surveyor] protocol.
`NN_RESPONDENT`:: xref:nng_respondent.7.adoc[Respondent] protocol.
`NN_BUS`:: xref:nng_bus.7.adoc[Bus] protocol.

== RETURN VALUES

This function returns a valid socket number on success, and -1 on failure.

== ERRORS

[horizontal]
`ENOMEM`:: Insufficient memory is available.
`ENOTSUP`:: The protocol is not supported.
`ETERM`:: The library is shutting down.

== SEE ALSO

[.text-left]
xref:nng_socket.5.adoc[nng_socket(5)],
xref:nn_close.3compat.adoc[nn_close(3compat)],
xref:nn_errno.3compat.adoc[nn_errno(3compat)],
xref:nng_compat.3compat.adoc[nng_compat(3compat)],
xref:nng.7.adoc[nng(7)]
