= nn_sendmsg(3compat)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nn_sendmsg - send message (compatible API)

== SYNOPSIS

[source, c]
----
#include <nanomsg/nn.h>

int nn_sendmsg(int sock, const struct nn_msghdr *hdr, int flags);
----

== DESCRIPTION

The `nn_sendmsg()` function sends the message described by _hdr_ using the
socket _sock_.

NOTE: This function is provided for API
xref:nng_compat.3compat.adoc[compatibility] with legacy _libnanomsg_.
Consider using the relevant xref:libnng.3.adoc[modern API] instead.

The _flags_ field may contain the special flag `NN_DONTWAIT`.
In this case, if the socket is unable to accept more data for sending,
the operation shall not block, but instead will fail with the error `EAGAIN`.

The _hdr_ points to a structure of type `struct nn_msghdr`, which has the
following definition:

[source, c]
----
struct nn_iovec {
    void * iov_base;
    size_t iov_len;
};

struct nn_msghdr {
    struct nn_iovec *msg_iov;
    int              msg_iovlen;
    void *           msg_control;
    size_t           msg_controllen;
};
----

The `msg_iov` is an array of gather items, permitting the message
to be spread into different memory blocks.
There are `msg_iovlen` elements in this array, each of which
has the base address (`iov_base`) and length (`iov_len`) indicated.

For buffers allocated for zero copy
(such as by xref:nn_allocmsg.3compat.adoc[`nn_allocmsg()`]), the value
of `iov_base` should be the address of the pointer to the buffer,
rather than the address of the buffer itself.
In this case, the value of `iov_len` should be `NN_MSG`,
as the length is inferred from the allocated message.
If the `msg_iovlen` field is `NN_MSG`, then this function will free
the associated buffer after it is done with it, if it returns successfully.
(If the function returns with an error, then the caller retains ownership
of the associated buffer and may retry the operation or free the buffer
at its choice.)

The values of `msg_control` and `msg_controllen` describe a buffer
of ancillary data to send the message.
This is currently only useful to provide the message headers
used with xref:nng.7.adoc#raw_mode[raw mode] sockets.
In all other circumstances these fields should be zero.
Details about this structure are covered in
xref:nn_cmsg.3compat.adoc[`nn_cmsg(3compat)`].

NOTE: The send operation is performed asynchronously, and may not have
completed before this function returns control to the caller.

== RETURN VALUES

This function returns the number of bytes sent on success, and -1 on error.

== ERRORS

[horizontal]
`EAGAIN`:: The operation would block.
`EBADF`:: The socket _sock_ is not open.
`EFSM`:: The socket cannot send in this state.
`EINVAL`:: The _hdr_ is invalid.
`ENOTSUP`:: This protocol cannot send.
`ETIMEDOUT`:: Operation timed out.

== SEE ALSO

[.text-left]
xref:nn_cmsg.3compat.adoc[nn_cmsg(3compat)],
xref:nn_errno.3compat.adoc[nn_errno(3compat)],
xref:nn_recv.3compat.adoc[nn_recv(3compat)],
xref:nn_send.3compat.adoc[nn_send(3compat)],
xref:nn_socket.3compat.adoc[nn_socket(3compat)],
xref:nng_compat.3compat.adoc[nn_compat(3compat)],
xref:nng.7.adoc[nng(7)]
