= nng_pipe_getopt(3)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_pipe_getopt - get pipe option

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>

int nng_pipe_getopt(nng_pipe p, const char *opt, void *val, size_t *valszp);

int nng_pipe_getopt_bool(nng_pipe p, const char *opt, int *bvalp);

int nng_pipe_getopt_int(nng_pipe p, const char *opt, int *ivalp);

int nng_pipe_getopt_ms(nng_pipe p, const char *opt, nng_duration *durp);

int nng_dialer_getopt_ptr(nng_pipe p, const char *opt, void **ptr);

int nng_pipe_getopt_sockaddr(nng_pipe p, const char *opt, nng_sockaddr *sap);

int nng_pipe_getopt_string(nng_pipe p, const char *opt, char **strp);

int nng_pipe_getopt_size(nng_pipe p, const char *opt, size_t *zp);

int nng_pipe_getopt_uint64(nng_pipe p, const char *opt, uint64_t *u64p);
----

== DESCRIPTION

(((options, pipe)))
The `nng_pipe_getopt()` functions are used to retrieve option values for
the <<nng_pipe.5#,pipe>> _p_.
The actual options that may be retrieved in this way
vary, and many are documented in <<nng_options.5#,nng_options(5)>>.
Additionally some transport-specific options and protocol-specific options are
documented with the transports andp protocols themselves.

NOTE: All "`options`" on a pipe are read-only values, and intended to
facilitate understanding the identity of an associated peer.
Modification of options must be done on the listener or dialer using either
`<<nng_listener_setopt.3#,nng_listener_setopt()>>` or
`<<nng_dialer_getopt.3#,nng_dialer_setopt()>>`.

Any option that is set on a dialer or listener will normally be retrievable
from pipes created by that dialer or listener.

=== Forms

In all of these forms, the option _opt_ is retrieved from the pipe _p_.

The details of the type, size, and semantics of the option will depend
on the actual option, and will be documented with the option itself.

==== `nng_pipe_getopt()`

This is untyped, and can be used to retrieve the value of any option.
A pointer to a buffer to receive the value in _val_, and the size of the
buffer shall be stored at the location referenced by _valszp_.

When the function returns, the actual size of the data copied (or that
would have been copied if sufficient space were present) is stored at
the location referened by _valszp_.
If the caller's buffer is not large enough to hold the entire object,
then the copy is truncated.
Therefore the caller should check for trncation by verifying that the
size returned in _valszp_ does not exceed the original buffer size.

It is acceptable to pass `NULL` for _val_ if the value in _valszp_ is zero.
This can be used to determine the size of the buffer needed to receive
the object.

TIP: Generally, it will be easier to use one of the typed forms instead.

==== `nng_pipe_getopt_bool()`

This function is for options which take a boolean (`bool`).
The value will be stored at _bvalp_.

==== `nng_pipe_getopt_int()`

This function is for options which take an integer (`int`) or boolean (`bool`).
The value will be stored at _ivalp_.  For booleans the value will be eiher 0
(`false`) or 1 (`true`).

==== `nng_pipe_getopt_ms()`

This function is used to retrieve time durations
(`<<nng_duration.5#,nng_duration>>`) in milliseconds, which are stored in
_durp_.

==== `nng_pipe_getopt_ptr()`
This function is used to retrieve a pointer, _ptr_, to structured data.
The data referenced by _ptr_ is generally managed using other functions.
Note that this form is somewhat special in that the object is generally
not copied, but instead the *pointer* to the object is copied.

==== `nng_pipe_getopt_size()`

This function is used to retrieve a size into the pointer _zp_,
typically for buffer sizes, message maximum sizes, and similar options.

==== `nng_pipe_getopt_sockaddr()`

This function is used to retrieve an `<<nng_sockaddr.5#,nng_sockaddr>>`
into _sap_.

==== `nng_pipe_getopt_string()`

This function is used to retrieve a string into _strp_.
This string is created from the source using `<<nng_strdup.3#,nng_strdup()>>`
and consequently must be freed by the caller using
`<<nng_strfree.3#,nng_strfree()>>` when it is no longer needed.

==== `nng_pipe_getopt_uint64()`

This function is used to retriev a 64-bit unsigned value into the value
referenced by _u64p_.
This is typically used for options
related to identifiers, network numbers, and similar.

== RETURN VALUES

These functions return 0 on success, and non-zero otherwise.

== ERRORS

`NNG_EBADTYPE`:: Incorrect type for option.
`NNG_ECLOSED`:: Parameter _p_ does not refer to an open pipe.
`NNG_ENOTSUP`:: The option _opt_ is not supported.
`NNG_ENOMEM`:: Insufficient memory exists.
`NNG_EINVAL`:: Size of destination _val_ too small for object.
`NNG_EWRITEONLY`:: The option _opt_ is write-only.

== SEE ALSO

<<nng_dialer_setopt.3#,nng_dialer_setopt(3)>>
<<nng_getopt.3#,nng_getopt(3)>>,
<<nng_listener_setopt.3#,nng_listener_setopt(3)>>
<<nng_msg_get_pipe.3#,nng_msg_get_pipe(3)>>
<<nng_strdup.3#,nng_strdup(3)>>,
<<nng_strerror.3#,nng_strerror(3)>>,
<<nng_strfree.3#,nng_strfree(3)>>,
<<nng_duration.5#,nng_duration(5)>>,
<<nng_options.5#,nng_options(5)>>,
<<nng_pipe.5#,nng_pipe(5)>>,
<<nng_sockaddr.5#,nng_sockaddr(5)>>,
<<nng.7#,nng(7)>>
