= nng_tls_getopt(3tls)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
// Copyright 2019 Devolutions <info@devolutions.net>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_tls_getopt - get option from TLS connection

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/supplemental/tls/tls.h>

int nng_tls_getopt(nng_tls *conn, const char *name, void *data, size_t *sizep);
----

== DESCRIPTION

The `nng_tls_getopt()` is used to retrieve the value of the option _name_ for
the <<nng_tls.5#,TLS connection>> _conn_.
The size of the buffer located at _data_ to receive the copy is passed by the
caller at the location referenced by _sizep_.
If this size is sufficient to hold the entire object, the object is copied into
the buffer specified by _data_.
In either event, the size of the source object (the amount of data copied,
or that would have been copied if sufficient space were available) is stored
at the location of _sizep_.

=== Options

The options specifically suppported for retrieval from TLS connections are:

* <<nng_options.5#NNG_OPT_LOCADDR,`NNG_OPT_LOCADDR`>>
* <<nng_options.5#NNG_OPT_REMADDR,`NNG_OPT_REMADDR`>>
* <<nng_tcp_options.5#NNG_OPT_TCP_KEEPALIVE,`NNG_OPT_TCP_KEEPALIVE`>>
* <<nng_tcp_options.5#NNG_OPT_TCP_NODELAY,`NNG_OPT_TCP_NODELAY`>>
* <<nng_tls_options.5#NNG_OPT_TLS_VERIFIED,`NNG_OPT_TLS_VERIFIED`>>

== RETURN VALUES

This function returns 0 on success, and non-zero otherwise.

== ERRORS

[horizontal]
`NNG_ECLOSED`:: The connection _conn_ is closed.
`NNG_EINVAL`:: There was insufficient space to receive the object.
	The amount of data actually needed is returned in _sizep_.
`NNG_ENOTSUP`:: The option _name_ is not supported.
`NNG_EWRITEONLY`:: The option _name_ may not read.

== SEE ALSO

[.text-left]
<<nng_strerror.3#,nng_strerror(3)>>,
<<nng_tls_setopt.3tls#,nng_tls_setopt(3tls)>>,
<<nng_options.5#,nng_options(5)>>,
<<nng_tcp_options.5#,nng_tcp_options(5)>>,
<<nng_tls.5#,nng_tlsp(5)>>,
<<nng_tls_options.5#,nng_tls_options(5)>>
