= nng_recvmsg(3)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_recvmsg - recv message

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>

int nng_recvmsg(nng_socket s, nng_msg **msgp, int flags);
----

== DESCRIPTION

The `nng_recvmsg()` receives a message on socket _s_, storing the
received message at the location pointed to by _msgp_.

TIP: Using this function gives access to the message structure, and thus may
offer more functionality than the simpler xref:nng_recv.3.adoc[`nng_recv()`] function.

The _flags_ may contain the following value:

`NNG_FLAG_NONBLOCK`::
  The function returns immediately, even if no message is available.
  Without this flag, the function will wait until a message is received
  by the socket _s_, or any configured timer expires.

NOTE: The semantics of what receiving a message means vary from protocol to
protocol, so examination of the protocol documentation is encouraged.
(For example, with an xref:nng_req.7.adoc[_req_] socket a message may only be received
after a request has been sent, and an xref:nng_sub.7.adoc[_sub_] socket
may only receive messages corresponding to topics to which it has subscribed.)
Furthermore, some protocols may not support receiving data at all, such as
xref:nng_pub.7.adoc[_pub_].

== RETURN VALUES

This function returns 0 on success, and non-zero otherwise.

== ERRORS

[horizontal]
`NNG_EAGAIN`:: The operation would block, but `NNG_FLAG_NONBLOCK` was specified.
`NNG_ECLOSED`:: The socket _s_ is not open.
`NNG_EINVAL`:: An invalid set of _flags_ was specified.
`NNG_ENOMEM`:: Insufficient memory is available.
`NNG_ENOTSUP`:: The protocol for socket _s_ does not support receiving.
`NNG_ESTATE`:: The socket _s_ cannot receive data in this state.
`NNG_ETIMEDOUT`:: The operation timed out.

== SEE ALSO

[.text-left]
xref:nng_msg_free.3.adoc[nng_msg_free(3)],
xref:nng_recv.3.adoc[nng_recv(3)],
xref:nng_sendmsg.3.adoc[nng_sendmsg(3)],
xref:nng_strerror.3.adoc[nng_strerror(3)],
xref:nng.7.adoc[nng(7)]
