= nng_socket_id(3)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_socket_id - return numeric socket identifier

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>

int nng_socket_id(nng_socket s);
----

== DESCRIPTION

The `nng_socket_id()` function returns a positive identifier for the socket _s_,
if it is valid.
Otherwise it returns `-1`.

NOTE: A socket is considered valid if it was ever opened with a protocol
constructor, such as the xref:nng_req_open.3.adoc[`nng_req0_open()`] function.
Sockets that are allocated on the stack or statically should be
initialized with the macro
xref:nng_socket.5.adoc#NNG_SOCKET_INITIALIZER[`NNG_SOCKET_INITIALIZER`]
to ensure that they cannot be confused with a valid socket before they are opened.

== RETURN VALUES

This function returns the positive value for the socket identifier, or
`-1` if the socket is invalid.

== ERRORS

None.

== SEE ALSO

[.text-left]
xref:nng_socket.5.adoc[nng_socket(5)],
xref:nng.7.adoc[nng(7)]
