= nng_tls_listener_close(3tls)
//
// Copyright 2019 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
// Copyright 2019 Devolutions <info@devolutions.net>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_tls_listener_close - close TLS listener

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/supplemental/tls/tls.h>

void nng_tls_listener_close(nng_tls_listener *l);
----

== DESCRIPTION

The `nng_tls_listener_close()` function closes the supplied TLS listener _l_,
but does not free the underlying resources associated with it.

If any <<nng_tls_listener_accept.3tls#,accept>> operations using _l_
are in progress, they will be terminated with an `NNG_ECLOSED` error condition.

Furthermore any future accesses to the listener _l_ will also result in
`NNG_ECLOSED`.

NOTE: This function does not release the memory for the listener, so the
application should still free the memory using
<<nng_tls_listener_free.3tls#,`nng_tls_listener_free()`>>
once it is certain that nothing else is using it.

== RETURN VALUES

None.

== ERRORS

None.

== SEE ALSO

[.text-left]
<<nng_strerror.3#,nng_strerror(3)>>,
<<nng_tls_listener_alloc.3tls#,nng_tls_listener_alloc(3tls)>>,
<<nng_tls_listener_accept.3tls#,nng_tls_listener_accept(3tls)>>,
<<nng_tls_listener_free.3tls#,nng_tls_listener_free(3tls)>>,
<<nng_tls_listener.5#,nng_tls_listener(5)>>
