= nng_pipe(5)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_pipe - communications pipe

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>

typedef struct nng_pipe_s nng_pipe;
----

== DESCRIPTION

(((pipe)))(((connection)))
An `nng_pipe` is a handle to a "`pipe`", which can be thought of as a single
connection.
(In most cases this is actually the case -- the pipe is an abstraction for a
single TCP or IPC connection.)
Pipes are associated with either the listener or dialer that created them,
and therefore are also automatically associated with a single socket.

IMPORTANT: The `nng_pipe` structure is always passed by value (both
for input parameters and return values), and should be treated opaquely.
Passing structures this way ensures gives the compiler a chance to perform
accurate type checks in functions passing values of this type.

TIP: Most applications should never concern themselves with individual pipes.
However it is possible to access a pipe when more information about the
source of a message is needed, or when more control is required over
message delivery.

Pipe objects are created by dialers (`<<nng_dialer.5#,nng_dialer>>` objects)
and listeners (`<<nng_listener.5#,nng_listener>>` objects), which can be
thought of as "`owning`" the pipe.

Pipe objects may be destroyed by the
`<<nng_pipe_close.3#,nng_pipe_close()>>` function.
They are also closed when their "`owning`" dialer or listener is closed,
or when the remote peer closes the underlying connection.

[[NNG_PIPE_INITIALIZER]]
=== Initialization

A pipe may be initialized using the macro `NNG_PIPE_INITIALIZER`
before it is opened, to prevent confusion with valid open pipes.

For example:

[source, c]
----
nng_pipe p = NNG_PIPE_INITIALIZER;
----

== SEE ALSO

[.text-left]
<<nng_msg_get_pipe.3#,nng_msg_get_pipe(3)>>,
<<nng_pipe_close.3#,nng_pipe_close(3)>>,
<<nng_pipe_getopt.3#,nng_pipe_getopt(3)>>,
<<nng_pipe_dialer.3#,nng_pipe_dialer(3)>>,
<<nng_pipe_id.3#,nng_pipe_id(3)>>,
<<nng_pipe_listener.3#,nng_pipe_listener(3)>>,
<<nng_pipe_socket.3#,nng_pipe_socket(3)>>,
<<nng_dialer.5#,nng_dialer(5)>>,
<<nng_listener.5#,nng_listener(5)>>,
<<nng_options.5#,nng_options(5)>>,
<<nng.7#,nng(7)>>
