= nng_ctx_open(3)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_ctx_open - create context

== SYNOPSIS

[source,c]
----
#include <nng/nng.h>

int nng_ctx_open(nng_ctx *ctxp, nng_socket s);
----

== DESCRIPTION

The `nng_ctx_open()` function creates a separate ((context)) to be used with
the socket _s_,
and returns it at the location pointed by _ctxp_.

NOTE: Not every protocol supports creation of separate contexts.

Contexts allow the independent and concurrent use of stateful operations
using the same socket.
For example, two different contexts created on a xref:nng_rep.7.adoc[_rep_]
socket can each receive requests, and send replies to them, without any
regard to or interference with each other.

(((raw mode)))
TIP: Using contexts is an excellent way to write simpler concurrent
applications, while retaining the benefits of the protocol-specific
advanced processing, avoiding the need to bypass that with
xref:nng.7.adoc#raw_mode[raw mode] sockets.

NOTE: Use of contexts with xref:nng.7.adoc#raw_mode[raw mode] sockets is
nonsensical, and not supported.

== RETURN VALUES

This function returns 0 on success, and non-zero otherwise.

== ERRORS

[horizontal]
`NNG_ENOMEM`:: Insufficient memory is available.
`NNG_ENOTSUP`:: The protocol does not support separate contexts, or the socket was opened in raw mode.

== SEE ALSO

[.text-left]
xref:nng_ctx_close.3.adoc[nng_ctx_close(3)],
xref:nng_ctx_getopt.3.adoc[nng_ctx_getopt(3)],
xref:nng_ctx_recv.3.adoc[nng_ctx_recv(3)],
xref:nng_ctx_send.3.adoc[nng_ctx_send(3)],
xref:nng_ctx_setopt.3.adoc[nng_ctx_setopt(3)],
xref:nng_strerror.3.adoc[nng_strerror(3)],
xref:nng_ctx.5.adoc[nng_ctx(5)],
xref:nng_socket.5.adoc[nng_socket(5)],
xref:nng_rep.7.adoc[nng_rep(7)],
xref:nng_req.7.adoc[nng_req(7)],
xref:nng.7.adoc[nng(7)]
