= nng_tls_config_cert_key_file(3tls)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_tls_config_cert_key_file - load own certificate and key from file

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/supplemental/tls/tls.h>

int nng_tls_config_cert_key_file(nng_tls_config *cfg, const char *path,
    const char *pass);
----

== DESCRIPTION

The `nng_tls_config_cert_key_file()` function loads a certificate (or
certificate chain) and a ((private key)) from the file named by _path_.

The file must contain both the https://tools.ietf.org/html/rfc7468[PEM]
encoded certificate and associated private key, which will be used when
establishing TLS sessions using _cfg_.
It may contain additional certificates leading to a validation chain,
with the leaf certificate first.
There is no need to include the self-signed root, as the peer
will need to have that already in order to perform its own validation.

The private key may be encrypted with a password, in which can be supplied in
_pass_.
The value `NULL` should be supplied for _pass_ if the key is not encrypted.

On servers, it is possible to call this function multiple times for the
same configuration.
This can be useful for specifying different parameters
to be used for different cryptographic algorithms.

== RETURN VALUES

This function returns 0 on success, and non-zero otherwise.

== ERRORS

[horizontal]
`NNG_ENOMEM`:: Insufficient memory is available.
`NNG_EBUSY`:: The configuration _cfg_ is already in use, and cannot be modified.
`NNG_EINVAL`:: The contents of _path_ are invalid.
`NNG_ENOENT`:: The file named by _path_ does not exist.
`NNG_EPERM`:: The file named by _path_ cannot be opened.

== SEE ALSO

[.text-left]
xref:nng_strerror.3.adoc[nng_strerror(3)],
xref:nng_tls_config_alloc.3tls.adoc[nng_tls_config_alloc(3tls)],
xref:nng_tls_config_own_cert.3tls.adoc[nng_tls_config_own_cert(3tls)],
xref:nng.7.adoc[nng(7)]
