= nng_ipc_dialer_free(3ipc)
//
// Copyright 2019 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
// Copyright 2019 Devolutions <info@devolutions.net>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_ipc_dialer_free - free IPC dialer

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/supplemental/ipc/ipc.h>

void nng_ipc_dialer_free(nng_ipc_dialer *d);
----

== DESCRIPTION

The `nng_ipc_dialer_free()` function closes the supplied IPC dialer _d_,
and frees the underlying resources associated with it.

If any <<nng_ipc_dialer_dial.3ipc#,dial>> operations
 using _d_ are
in progress, they will be terminated with an `NNG_ECLOSED` error condition.

WARNING: It is important that the application ensure that no further accesses
are made to _d_, as the memory backing it will be reclaimed for other uses.

== RETURN VALUES

None.

== ERRORS

None.

== SEE ALSO

[.text-left]
<<nng_strerror.3#,nng_strerror(3)>>,
<<nng_ipc_dialer_alloc.3ipc#,nng_ipc_dialer_alloc(3ipc)>>,
<<nng_ipc_dialer_close.3ipc#,nng_ipc_dialer_close(3ipc)>>,
<<nng_ipc_dialer_dial.3ipc#,nng_ipc_dialer_dial(3ipc)>>,
<<nng_ipc_dialer.5#,nng_ipc_dialer(5)>>
