= nng_mqtt_client_open(3)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_mqtt_client_open - open mqtt socket client

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/mqtt/mqtt_client.h>

int nng_mqtt_client_open(nng_socket *sock);
----

== DESCRIPTION

The `nng_mqtt_client_open()` Create a MQTT client dose nit connect it.
Note that MQTT sockets can be connected to at most a single server.

Must create MQTT CONNECT message for *dialer* by message functions: xref:nng_mqtt_msg_alloc.3.adoc[nng_mqtt_msg_alloc()], xref:nng_mqtt_msg_set_connect.3.adoc[nng_mqtt_msg_set_connect()]

client demo snippet
[source, c]
----
if ((rv = nng_mqtt_client_open(&sock)) != 0) {
    fatal("nng_socket", rv);
}

nng_msg *msg;
nng_mqtt_msg_alloc(&msg, 0);
nng_mqtt_msg_set_packet_type(msg, NNG_MQTT_CONNECT);

if ((rv = nng_dialer_create(&dialer, sock, url)) != 0) {
    fatal("nng_dialer_create", rv);
}

nng_dialer_set_ptr(dialer, NNG_OPT_MQTT_CONNMSG, msg);
nng_dialer_start(dialer, NNG_FLAG_NONBLOCK);
----

== RETURN VALUES

This function returns 0 on success, and non-zero otherwise.

== ERRORS

[horizontal]
`NNG_ENOTSUP`:: MQTT not supported.

== SEE ALSO

[.text-left]
xref:nng_dialer_create.3.adoc[nng_dialer_create()]
xref:nng_mqtt_callback_function.3.adoc[nng_mqtt_cb()]
xref:nng_mqtt_msg_alloc.3.adoc[nng_mqtt_msg_alloc()]
xref:nng_mqtt_msg_set_connect.3.adoc[nng_mqtt_msg_set_connect()]
xref:nng_strerror.3.adoc[nng_strerror(3)],
xref:nng_url_parse.3.adoc[nng_url_parse(3)],
xref:nng.7.adoc[nng(7)]
