= nng_pipe(5)
//
// Copyright 2020 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_pipe - communications pipe

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>

typedef struct nng_pipe_s nng_pipe;
----

== DESCRIPTION

(((pipe)))(((connection)))
An `nng_pipe` is a handle to a pipe object, which can be thought of as a single
connection.
(In most cases this is actually the case -- the pipe is an abstraction for a
single TCP or IPC connection.)
Pipes are associated with either the listener or dialer that created them,
and therefore are also automatically associated with a single socket.

IMPORTANT: The `nng_pipe` structure is always passed by value (both
for input parameters and return values), and should be treated opaquely.
Passing structures this way gives the compiler a chance to perform
accurate type checks in functions passing values of this type.

TIP: Most applications should never concern themselves with individual pipes.
However it is possible to access a pipe when more information about the
source of a message is needed, or when more control is required over
message delivery.

Pipe objects are created by dialers (xref:nng_dialer.5.adoc[`nng_dialer`] objects)
and listeners (xref:nng_listener.5.adoc[`nng_listener`] objects).

Pipe objects may be destroyed by the
xref:nng_pipe_close.3.adoc[`nng_pipe_close()`] function.
They are also closed when the dialer or listener that created them is closed,
or when the remote peer closes the underlying connection.

[[NNG_PIPE_INITIALIZER]]
=== Initialization

A pipe may be initialized using the macro `NNG_PIPE_INITIALIZER`
before it is opened, to prevent confusion with valid open pipes.

For example:

[source, c]
----
nng_pipe p = NNG_PIPE_INITIALIZER;
----

== SEE ALSO

[.text-left]
xref:nng_msg_get_pipe.3.adoc[nng_msg_get_pipe(3)],
xref:nng_pipe_close.3.adoc[nng_pipe_close(3)],
xref:nng_pipe_getopt.3.adoc[nng_pipe_getopt(3)],
xref:nng_pipe_dialer.3.adoc[nng_pipe_dialer(3)],
xref:nng_pipe_id.3.adoc[nng_pipe_id(3)],
xref:nng_pipe_listener.3.adoc[nng_pipe_listener(3)],
xref:nng_pipe_socket.3.adoc[nng_pipe_socket(3)],
xref:nng_dialer.5.adoc[nng_dialer(5)],
xref:nng_listener.5.adoc[nng_listener(5)],
xref:nng_options.5.adoc[nng_options(5)],
xref:nng.7.adoc[nng(7)]
