= nng_msg_header_insert(3)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_msg_header_insert, nng_msg_header_insert_u32 - prepend to message header

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>

int nng_msg_header_insert(nng_msg *msg, const void *val, size_t size);

int nng_msg_header_insert_u32(nng_msg *msg, uint32_t val32);
----

== DESCRIPTION

The `nng_msg_header_insert()` and `nng_msg_header_insert_u32()` functions
prepend data to the front of the headers of message _msg_, reallocating
if necessary.
The first function prepends _size_ bytes, copying them from _val_.  The
second function prepends the value _val32_ in network-byte order (big-endian).

== RETURN VALUES

This function returns 0 on success, and non-zero otherwise.

== ERRORS

`NNG_ENOMEM`:: Insufficient free memory exists.

== SEE ALSO

<<nng_msg_alloc.3#,nng_msg_alloc(3)>>,
<<nng_msg_header.3#,nng_msg_header(3)>>,
<<nng_msg_header_append.3#,nng_msg_header_append(3)>>,
<<nng_msg_header_chop.3#,nng_msg_header_chop(3)>>,
<<nng_msg_header_len.3#,nng_msg_header_len(3)>>,
<<nng_msg_header_trim.3#,nng_msg_header_trim(3)>>,
<<nng_msg_free.3#,nng_msg_free(3)>>,
<<nng_msg_realloc.3#,nng_msg_realloc(3)>>,
<<nng_strerror.3#,nng_strerror(3)>>,
<<nng.7#,nng(7)>>
