= nng_tls_listener_accept(3tls)
//
// Copyright 2019 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
// Copyright 2019 Devolutions <info@devolutions.net>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_tls_listener_accept - accept incoming TLS connection

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/supplemental/tls/tls.h>

void nng_tls_listener_accept(nng_tls_listener *l, nng_aio *aio);
----

== DESCRIPTION

The `nng_tls_listener_accept()` attempts to accept an incoming TLS connection
from a remote peer, using the listener _l_.
The operation is completed asynchronously, using _aio_.

This operation can only be done after the listener is already bound to
a TCP port and is <<nng_tls_listener_listen.3tls#,listening>>.

If a connection is successfully established, the _aio_ will have the
resulting <<nng_tls.5#,`nng_tls`>> stored as its first output.
(See <<nng_aio_get_output.3#,`nng_aio_get_output()`>>.)

The address of the remote peer can be determined using the
<<nng_options.5#NNG_OPT_REMADDR,`NNG_OPT_REMADDR`>> option with the
<<nng_tls_getopt.3tls#,`nng_tls_getopt()`>> function on the
returned <<nng_tls.5#,`nng_tls`>>.

== RETURN VALUES

None.

== ERRORS

[horizontal]
`NNG_ECANCELED`:: The operation was aborted.
`NNG_ECLOSED`:: The listener is closed.
`NNG_ECONNRESET`:: The connection was reset by the peer.
`NNG_ENOMEM`:: Insufficient free memory exists.
`NNG_ESTATE`:: The listener is not not listening.

== SEE ALSO

[.text-left]
<<nng_strerror.3#,nng_strerror(3)>>,
<<nng_tls_listener_alloc.3tls#,nng_tls_listener_alloc(3tls)>>,
<<nng_tls_listener_close.3tls#,nng_tls_listener_close(3tls)>>,
<<nng_tls_listener_free.3tls#,nng_tls_listener_free(3tls)>>,
<<nng_tls_listener_listen.3tls#,nng_tls_listener_listen(3tls)>>,
<<nng_aio.5#,nng_aio(5)>>,
<<nng_tls.5#,nng_tls(5)>>,
<<nng_options.5#,nng_options(5)>>,
<<nng_tls_listener.5#,nng_tls_listener(5)>>,
<<nng_tls_options.5#,nng_tls_options(5)>>
