= nng_mqtt_cb(3)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_mqtt_cb - mqtt client callback function structure

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#define NNG_OPT_MQTT_CONNMSG "mqtt-connect-msg"

#include <nng/mqtt/mqtt_client.h>
typedef struct {
	char *name;
	void (*on_connected)(void *, nng_msg *);
	void (*on_disconnected)(void *, nng_msg *);
	void *connect_arg;
	void *disconn_arg;
} nng_mqtt_cb;
----

== DESCRIPTION

The `nng_mqtt_cb` define for MQTT client *connect* and *disconnect* callback functions,
and set by xref:nng_dialer_set.3.adoc[nng_dialer_set_cb()] 

client demo snippet:
[source, c]
----
nng_mqtt_cb user_cb = {
    .name            = "user_cb",
    .on_connected    = connect_cb,
    .on_disconnected = disconnect_cb,
    .connect_arg     = "arg",
    .disconn_arg     = "arg",
};

nng_dialer_set_cb(dialer, &user_cb);
----

== RETURN VALUES

This function returns 0 on success, and non-zero otherwise.

== ERRORS

[horizontal]
`NNG_ENOTSUP`:: MQTT not supported.

== SEE ALSO

[.text-left]
xref:nng_dialer_create.3.adoc[nng_dialer_create()]
xref:nng_mqtt_msg_alloc.3.adoc[nng_mqtt_msg_alloc()]
xref:nng_mqtt_msg_set_connect.3.adoc[nng_mqtt_msg_set_connect()]
xref:nng_strerror.3.adoc[nng_strerror(3)],
xref:nng_url_parse.3.adoc[nng_url_parse(3)],
xref:nng.7.adoc[nng(7)]
