= nng_ctx_id(3)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_ctx_id - return numeric context identifier

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>

int nng_ctx_id(nng_ctx c);
----

== DESCRIPTION

The `nng_ctx_id()` function returns a positive identifier for the context _c_,
if it is valid.
Otherwise it returns `-1`.

NOTE: A context is considered valid if it was ever opened with
`<<nng_ctx_open.3#,nng_ctx_open()>>` function.
Contexts that are allocated on the stack or statically should be
initialized with the macro
`<<nng_ctx.5#NNG_CTX_INITIALIZER,NNG_CTX_INITIALIZER>>` to ensure that
they cannot be confused with a valid context before they are opened.

== RETURN VALUES

This function returns the positive value for the context identifier, or
`-1` if the context is invalid.

== ERRORS

None.

== SEE ALSO

[.text-left]
<<nng_ctx.5#,nng_ctx(5)>>,
<<nng.7#,nng(7)>>
