= nng_close(3)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_close - close socket

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>

int nng_close(nng_socket s);
----

== DESCRIPTION

The `nng_close()` function closes the supplied socket, _s_.
Messages that have been submitted for sending may be flushed or delivered,
depending upon the transport and the setting of the
`<<nng_options.5#NNG_OPT_LINGER,NNG_OPT_LINGER>>` option.

Further attempts to use the socket after this call returns will result
in `NNG_ECLOSED`.
Threads waiting for operations on the socket when this
call is executed may also return with an `NNG_ECLOSED` result.

== RETURN VALUES

This function returns 0 on success, and non-zero otherwise.

== ERRORS

`NNG_ECLOSED`:: The socket _s_ is already closed or was never opened.

== SEE ALSO

<<nng_strerror.3#,nng_strerror(3)>>,
<<nng_options.5#,nng_options(5)>>,
<<nng_socket.5#,nng_socket(5)>>,
<<nng.7#,nng(7)>>
