= nng_tls_listener(5)
//
// Copyright 2019 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
// Copyright 2019 Devolutions <info@devolutions.net>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_tls_listener - TLS listener

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/supplemental/tls/tls.h>

typedef struct nng_tls_dialer_s nng_tls_dialer;
----

== DESCRIPTION

(((TLS, listener)))
An `nng_tls_listener` is a handle to a TLS "`listener`", which is responsible
for accepting connections (<<nng_tls.5#,`nng_tls`>> objects) from remote
systems.

NOTE: The `nng_tls_listener` object is used for raw TLS over TCP connections, and
should not be confused with a listener object created using the
<<nng_tls.7#,nng_tls(7)>> transport.

TIP: Most NNG applications should not use this, but instead use the
<<nng_tls.7#,nng_tls(7)>> transport instead.

== SEE ALSO

[.text-left]
<<nng_tls_listener_accept.3tls#,nng_tls_listener_accept(3tls)>>,
<<nng_tls_listener_alloc.3tls#,nng_tls_listener_alloc(3tls)>>,
<<nng_tls_listener_close.3tls#,nng_tls_listener_close(3tls)>>,
<<nng_tls_listener_free.3tls#,nng_tls_listener_free(3tls)>>,
<<nng_tls_listener_getopt.3tls#,nng_tls_listener_getopt(3tls)>>,
<<nng_tls_listener_listen.3tls#,nng_tls_listener_listen(3tls)>>,
<<nng_tls_listener_setopt.3tls#,nng_tls_listener_setopt(3tls)>>,
<<nng_tls.5#,nng_tls(5)>>,
<<nng_tls_dialer.5#,nng_tls_dialer(5)>>,
<<nng_tls.7#,nng_tls(7)>>
