= nng_pull(7)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_pull - pull protocol

== SYNOPSIS

[source,c]
----
#include <nng/protocol/pipeline0/pull.h>
----

== DESCRIPTION

(((protocol, _pull_)))
The ((_pull_ protocol)) is one half of a ((pipeline pattern)).
The other half is the xref:nng_push.7.adoc[_push_] protocol.

In the pipeline pattern, pushers distribute messages to pullers.
Each message sent
by a pusher will be sent to one of its peer pullers,
chosen in a round-robin fashion
from the set of connected peers available for receiving.
This property makes this pattern useful in ((load-balancing)) scenarios.

=== Socket Operations

The xref:nng_pull_open.3.adoc[`nng_pull0_open()`] functions create a puller socket.
This socket may be used to receive messages, but is unable to send them.
Attempts to send messages will result in `NNG_ENOTSUP`.

When receiving messages, the _pull_ protocol accepts messages as
they arrive from peers.
If two peers both have a message ready, the
order in which messages are handled is undefined.

=== Protocol Versions

Only version 0 of this protocol is supported.
(At the time of writing, no other versions of this protocol have been defined.)

=== Protocol Options

The _pull_ protocol has no protocol-specific options.

=== Protocol Headers

The _pull_ protocol has no protocol-specific headers.

== SEE ALSO

[.text-left]
xref:nng_pull_open.3.adoc[nng_pull_open(3)],
xref:nng_push.7.adoc[nng_push(7)],
xref:nng.7.adoc[nng(7)],
