= nng_duration(5)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_duration - relative time in milliseconds

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>

typedef int32_t nng_duration;

#define NNG_DURATION_INFINITE (-1)
#define NNG_DURATION_DEFAULT  (-2)
#define NNG_DURATION_ZERO     (0)
----

== DESCRIPTION

An `nng_duration`(((duration))) is a relative time, measured in
milliseconds.
This type is most often used in conjunction with timers and timeouts.

A couple of special values have been set aside, and carry special meanings.

((`NNG_DURATION_DEFAULT`)):::
Indicates a context-specific default value should be used.

((`NNG_DURATION_INFINITE`)):::
Effectively an infinite duration; used most often to disable timeouts.

((`NNG_DURATION_ZERO`)):::
Zero length duration; used to perform a single polling operation.

== SEE ALSO

[.text-left]
xref:nng_options.5.adoc[nng_options(5)],
xref:nng.7.adoc[nng(7)]
