= nng_ipc_close(3ipc)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
// Copyright 2019 Devolutions <info@devolutions.net>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_ipc_close - close IPC connection

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/supplemental/ipc/ipc.h>

void nng_ipc_close(nng_ipc *conn);
----

== DESCRIPTION

The `nng_ipc_close()` function closes the supplied IPC connection, _conn_.

If any operations are pending (such as <<nng_ipc_send.3ipc#,`nng_ipc_send()`>>
or <<nng_ipc_recv.3ipc#,`nng_ipc_recv()`>>) they will be terminated with
an `NNG_ECLOSED` error condition.
Also, any new operations will fail with `NNG_ECLOSED` after the connection
is closed.

NOTE: Closing the connection while data is in transmission will likely
lead to loss of that data.
There is no automatic linger or flush to ensure that the socket send buffers
have completely transmitted.

NOTE: Closing the connection does not free the resources associated with it.
Once it is certain that no more operations are pending on the connection,
it should be freed with <<nng_ipc_free.3ipc#,`nng_ipc_free()`>>.

== RETURN VALUES

None.

== ERRORS

None.

== SEE ALSO

[.text-left]
<<nng_strerror.3#,nng_strerror(3)>>,
<<nng_ipc_free.3ipc#,nng_ipc_free(3ipc)>>,
<<nng_ipc_recv.3ipc#,nng_ipc_recv(3ipc)>>,
<<nng_ipc_send.3ipc#,nng_ipc_send(3ipc)>>,
<<nng_ipc.5#,nng_ipc(5)>>
