= nng_tcp_recv(3tcp)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_tcp_recv - receive from TCP connection

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/supplemental/tcp/tcp.h>

void nng_tcp_recv(nng_tcp *conn, nng_aio *aio);
----

== DESCRIPTION

The `nng_tcp_recv()` function starts an asynchronous receive from the
TCP connection _conn_, into the scatter/gather vector located in the
asynchronous I/O structure _aio_.

NOTE: The `<<nng_aio_set_iov.3#,nng_aio_set_iov()>>` function must have been
called first, to set the scatter/gather vector for _aio_.

This function returns immediately, with no return value.
Completion of the operation is signaled via the _aio_,
and the final result may be obtained via
`<<nng_aio_result.3#,nng_aio_result()>>`.
That result will either be zero or an error code.

The I/O operation completes as soon as at least one byte has been
received, or an error has occurred.
Therefore, the number of bytes read may be less than requested.
The actual number of bytes read can be determined with
`<<nng_aio_count.3#,nng_aio_count()>>`.

NOTE: While TCP has the notion of urgent (out-of-band) delivery, that is
used by very few protocols and this API does not support it.

== RETURN VALUES

None.

== ERRORS

[horizontal]
`NNG_ECANCELED`:: The operation was canceled.
`NNG_ECLOSED`:: The connection was closed.
`NNG_ECONNRESET`:: The peer closed the connection.
`NNG_EINVAL`:: The _aio_ does not contain a valid scatter/gather vector.
`NNG_ENOMEM`:: Insufficient free memory to perform the operation.
`NNG_ETIMEDOUT`:: Timeout waiting for data from the connection.

== SEE ALSO

[.text-left]
<<nng_aio_alloc.3#,nng_aio_alloc(3)>>,
<<nng_aio_count.3#,nng_aio_count(3)>>,
<<nng_aio_result.3#,nng_aio_result(3)>>,
<<nng_aio_set_iov.3#,nng_aio_set_iov(3)>>,
<<nng_tcp_close.3tcp#,nng_tcp_close(3tcp)>>,
<<nng_tcp_send.3tcp#,nng_tcp_send(3tcp)>>,
<<nng_tcp.5#,nng_tcp(5)>>,
<<nng_strerror.3#,nng_strerror(3)>>
