= nng_ipc_setopt(3ipc)
//
// Copyright 2019 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
// Copyright 2019 Devolutions <info@devolutions.net>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_ipc_setopt - set option on IPC connection

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/supplemental/ipc/ipc.h>

int nng_ipc_setopt(nng_ipc *conn, const char *name, const void *data, size_t size);
----

== DESCRIPTION

The `nng_ipc_setopt()` is used to set the option _name_ for the
<<nng_ipc.5#,IPC connection>> _conn_.
The value to set is copied from _data_, which should be _size_ bytes
in length.

=== Options

There are no options defined for modification on IPC connections at this time.

== RETURN VALUES

This function returns 0 on success, and non-zero otherwise.

== ERRORS

[horizontal]
`NNG_ECLOSED`:: The connection _conn_ is closed.
`NNG_EINVAL`:: Either _data_ or _size_ are invalid.
`NNG_ENOTSUP`:: The option _name_ is not supported.
`NNG_EREADONLY`:: The option _name_ may not be modified.

== SEE ALSO

[.text-left]
<<nng_ipc_getopt.3ipc#,nng_ipc_getopt(3ipc)>>,
<<nng_ipc_options.5#,nng_ipc_options(5)>>,
<<nng_options.5#,nng_options(5)>>,
<<nng_strerror.3#,nng_strerror(3)>>,
<<nng_ipc.5#,nng_ipc(5)>>
