= nng_tcp_listener_free(3tcp)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_tcp_listener_free - free TCP listener

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/supplemental/tcp/tcp.h>

void nng_tcp_listener_free(nng_tcp_listener *l);
----

== DESCRIPTION

The `nng_tcp_listener_free()` function closes the supplied TCP listener _l_,
and frees the underlying resources associated with it.

If any accept operations
(see `<<nng_tcp_listener_accept.3tcp#,nng_tcp_listener_accept()>>`) using _l_
are in progress, they will be terminated with an `NNG_ECLOSED` error condition.

WARNING: It is important that the application ensure that no further accesses
are made to _l_, as the memory backing it will be reclaimed for other uses.

== RETURN VALUES

None.

== ERRORS

None.

== SEE ALSO

[.text-left]
<<nng_strerror.3#,nng_strerror(3)>>,
<<nng_tcp_listener_alloc.3tcp#,nng_tcp_listener_alloc(3tcp)>>,
<<nng_tcp_listener_close.3tcp#,nng_tcp_listener_close(3tcp)>>,
<<nng_tcp_listener.5#,nng_tcp_listener(5)>>
