= nng_http_conn_write_all(3http)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_http_conn_write_all - write all to HTTP connection

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/supplemental/http/http.h>

void nng_http_conn_write_all(nng_http_conn *conn, nng_aio *aio);
----

== DESCRIPTION

The `nng_http_conn_write_all()` function starts an asynchronous write to the
HTTP connection _conn_, into the scatter/gather vector located in the
asynchronous I/O structure _aio_.

NOTE: The `<<nng_aio_set_iov.3#,nng_aio_set_iov()>>` function must have been
called first, to set the scatter/gather vector for _aio_.

This function returns immediately, with no return value.
Completion of the operation is signaled via the _aio_, and the
final result may be obtained via `<<nng_aio_result.3#,nng_aio_result()>>`.
That result will either be zero or an error code.

The I/O operation completes only when the entire amount of data
requested has been written, or an error has occurred.
If the operation completes successfully, then the entire requested data has
been written.

It is still possible for a partial write to complete in the event of an error.
The actual number of bytes written can be determined with
`<<nng_aio_count.3#,nng_aio_count()>>`.

TIP: The main purpose for this function is to facilitate writing HTTP
body content.

TIP: Usually an HTTP request or response will have been written immediately
prior to this with `<<nng_http_conn_write_req.3http#,http_conn_write_req()>>` or
`<<nng_http_conn_write_res.3http#,http_conn_write_res()>>`.
In that case the request or response should have also contained
an `Content-Length` header, and possibly a `Content-Type` header.

TIP: An easier solution to sending HTTP content data, is to include the
content with the request or reply using a function like
`<<nng_http_req_copy_data.3http#,nng_http_req_copy_data()>>`.
In that case, the body data will be written automatically by the
`<<nng_http_conn_write_req.3http#,http_conn_write_req()>>` or
`<<nng_http_conn_write_req.3http#,http_conn_write_res()>>` function.

== RETURN VALUES

None.

== ERRORS

[horizontal]
`NNG_ECANCELED`:: The operation was canceled.
`NNG_ECLOSED`:: The connection was closed.
`NNG_ECONNRESET`:: The peer closed the connection.
`NNG_EINVAL`:: The _aio_ does not contain a valid scatter/gather vector.
`NNG_ENOMEM`:: Insufficient free memory to perform the operation.
`NNG_ENOTSUP`:: HTTP operations are not supported.
`NNG_ETIMEDOUT`:: Timeout waiting for data from the connection.

== SEE ALSO

[.text-left]
<<nng_aio_alloc.3#,nng_aio_alloc(3)>>,
<<nng_aio_count.3#,nng_aio_count(3)>>,
<<nng_aio_result.3#,nng_aio_result(3)>>,
<<nng_aio_set_iov.3#,nng_aio_set_iov(3)>>,
<<nng_http_client_connect.3http#,nng_http_client_connect(3http)>>,
<<nng_http_conn_write.3http#,nng_http_conn_write(3http)>>,
<<nng_http_conn_write_req.3http#,http_conn_write_req(3http)>>,
<<nng_http_conn_write_res.3http#,http_conn_write_res(3http)>>,
<<nng_http_req_copy_data.3http#,nng_http_req_copy_data(3http)>>,
<<nng_http_req_set_data.3http#,nng_http_req_set_data(3http)>>,
<<nng_http_res_copy_data.3http#,nng_http_res_copy_data(3http)>>,
<<nng_http_res_set_data.3http#,nng_http_res_set_data(3http)>>,
<<nng_strerror.3#,nng_strerror(3)>>,
<<nng.7#,nng(7)>>
