= nng_tcp_listener_close(3tcp)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_tcp_listener_close - close TCP listener

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/supplemental/tcp/tcp.h>

void nng_tcp_listener_close(nng_tcp_listener *l);
----

== DESCRIPTION

The `nng_tcp_listener_close()` function closes the supplied TCP listener _l_,
but does not free the underlying resources associated with it.

If any acceppt operations
(see `<<nng_tcp_listener_accept.3tcp#,nng_tcp_listener_accept()>>`) using _l_
are in progress, they will be terminated with an `NNG_ECLOSED` error condition.

Furthermore any future accesses to the listener _l_ will also result in
`NNG_ECLOSED`.

NOTE: This function does not release the memory for the listener, so the
application should still free the memory using
`<<nng_tcp_listener_free.3tcp#,nng_tcp_listener_free(3tcp)>>`
once it is certain that nothing else is using it.

== RETURN VALUES

None.

== ERRORS

None.

== SEE ALSO

[.text-left]
<<nng_strerror.3#,nng_strerror(3)>>,
<<nng_tcp_listener_alloc.3tcp#,nng_tcp_listener_alloc(3tcp)>>,
<<nng_tcp_listener_accept.3tcp#,nng_tcp_listener_accept(3tcp)>>,
<<nng_tcp_listener_free.3tcp#,nng_tcp_listener_free(3tcp)>>,
<<nng_tcp_listener.5#,nng_tcp_listener(5)>>
