= nng_aio_set_output(3)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_aio_set_output - set output result

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>

void nng_aio_set_output(nng_aio *aio, unsigned int index, void *result);
----

== DESCRIPTION

The `nng_aio_set_output()` function sets the output result at _index_
to _result_ for the asynchronous operation associated with _aio_.

The type and semantics of output results are determined by specific
operations; the operation must supply appropriate output results when
the operation completes successfully.

The valid values of _index_ range from zero (0) to three (3), as no operation
currently defined can return more than four results.
(This limit could increase in the future.)

NOTE:  Note that attempts to set results with an _index_ greater than
three (3) will be ignored.

An output result set with this function may be retrieved later with
the xref:nng_aio_get_output.3.adoc[`nng_aio_get_output()`] function.

== RETURN VALUES

None.

== ERRORS

None.

== SEE ALSO

[.text-left]
xref:nng_aio_alloc.3.adoc[nng_aio_alloc(3)],
xref:nng_aio_finish.3.adoc[nng_aio_finish(3)],
xref:nng_aio_get_output.3.adoc[nng_aio_get_output(3)],
xref:nng_aio_result.3.adoc[nng_aio_result(3)],
xref:nng_aio.5.adoc[nng_aio(5)],
xref:nng.7.adoc[nng(7)]
