= nng_tcp(5)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
// Copyright 2019 Devolutions <info@devolutions.net>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_tcp - TCP connection

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/supplemental/tcp/tcp.h>

typedef struct nng_tcp_s nng_tcp;
----

== DESCRIPTION

An `nng_tcp` (((TCP connection))) represents a connected stream.
TCP stream objects can be used to send or receive data.

NOTE: The `nng_tcp` object is used for raw TCP connections, and
should not be confused with a pipe object created using the
<<nng_tcp.7#,nng_tcp(7)>> transport.

TIP: Most NNG applications should not use this, but instead use the
<<nng_tcp.7#,nng_tcp(7)>> transport instead.

These objects are created either establishing an outgoing connection
with <<nng_tcp_dialer_dial.3tcp#,`nng_tcp_dialer_dial()`>> or by
accepting in incoming connection with
<<nng_tcp_listener_accept.3tcp#,`nng_tcp_listener_accept()`>>.

TCP connections are byte streams, and are "`reliable`" in that data
will not be delivered out of order, or with portions missing.

Data can be sent using <<nng_tcp_send.3tcp#,`nng_tcp_send()`>> or
received with <<nng_tcp_recv.3tcp#,`nng_tcp_recv()`>>.

When the connection is no longer needed, it should be freed with
<<nng_tcp_free.3tcp#,`nng_tcp_free()`>>.

TIP: It is possible to close the connection, without freeing it, by
using <<nng_tcp_close.3tcp#,`nng_tcp_close()`>>.

=== Options

The following options are applicable to TCP connections, and may be
accessed using the <<nng_tcp_getopt.3tcp#,`nng_tcp_getopt()`>> and
<<nng_tcp_setopt.3tcp#,`nng_tcp_setopt()`>> functions.

* <<nng_options.5#NNG_OPT_LOCADDR,`NNG_OPT_LOCADDR`>>
* <<nng_options.5#NNG_OPT_REMADDR,`NNG_OPT_REMADDR`>>
* <<nng_tcp_options.5#NNG_OPT_TCP_NO_DELAY,`NNG_OPT_TCP_NODELAY`>>
* <<nng_tcp_options.5#NNG_OPT_TCP_KEEPALIVE,`NNG_OPT_TCP_KEEPALIVE`>>
* <<nng_tcp_options.5#NNG_OPT_TCP_BOUND_PORT,`NNG_OPT_TCP_BOUND_PORT`>>

Other platform specific options may be available as well.

== SEE ALSO

[.text-left]
<<libnng.3#,libnng(3)>>,
<<nng_tcp_close.3tcp#,nng_tcp_close(3tcp)>>,
<<nng_tcp_dialer_dial.3tcp#,nng_tcp_dialer_dial(3tcp)>>,
<<nng_tcp_free.3tcp#,nng_tcp_free(3tcp)>>,
<<nng_tcp_getopt.3tcp#,nng_tcp_getopt(3tcp)>>,
<<nng_tcp_listener_accept.3tcp#,nng_tcp_listener_accept(3tcp)>>,
<<nng_tcp_recv.3tcp#,nng_tcp_recv(3tcp)>>,
<<nng_tcp_send.3tcp#,nng_tcp_send(3tcp)>>,
<<nng_tcp_setopt.3tcp#,nng_tcp_setopt(3tcp)>>,
<<nng_options.5#,nng_options(5)>>,
<<nng_tcp_options.5#,nng_tcp_options(5)>>,
<<nng.7#,nng(7)>>
