= nng_tls_listener_alloc(3tls)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
// Copyright 2019 Devolutions <info@devolutions.net>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_tls_listener_alloc - allocate TLS listener

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/supplemental/tls/tls.h>

int nng_tls_listener_alloc(nng_tls_listener *lp);
----

== DESCRIPTION

The `nng_tls_listener_alloc()` allocates a TLS listener, which can be used
to accept incoming connections over TLS, and stores a pointer to it
it in the location referenced by _lp_.

== RETURN VALUES

This function returns 0 on success, and non-zero otherwise.

== ERRORS

[horizontal]
`NNG_ENOMEM`:: Insufficient free memory exists.
`NNG_ENOTSUP`:: TLS support not configured in library.

== SEE ALSO

[.text-left]
<<nng_strerror.3#,nng_strerror(3)>>,
<<nng_tls_listener_accept.3tls#,nng_tls_listener_accept(3tls)>>,
<<nng_tls_listener_close.3tls#,nng_tls_listener_close(3tls)>>,
<<nng_tls_listener_free.3tls#,nng_tls_listener_free(3tls)>>,
<<nng_tls_listener_getopt.3tls#,nng_tls_listener_getopt(3tls)>>,
<<nng_tls_listener_listen.3tls#,nng_tls_listener_listen(3tls)>>,
<<nng_tls_listener_setopt.3tls#,nng_tls_listener_setopt(3tls)>>,
<<nng_tls_listener.5#,nng_tls_listener(5)>>
