= nng_mtx_unlock(3supp)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_mtx_unlock - unlock mutex

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/supplemental/util/platform.h>

void nng_mtx_unlock(nng_mtx *mtx);
----

== DESCRIPTION

The `nng_mtx_unlock()` relinquishes ownership of the mutex _mtx_ that
was previously acquired via xref:nng_mtx_lock.3supp.adoc[`nng_mtx_lock()`].

IMPORTANT: A mutex can _only_ be unlocked by the thread that locked it.
Attempting to unlock a mutex that is not owned by the caller will result
in undefined behavior.

== RETURN VALUES

None.

== ERRORS

None.

== SEE ALSO

[.text-left]
xref:nng_mtx_alloc.3supp.adoc[nng_mtx_alloc(3supp)],
xref:nng_mtx_lock.3supp.adoc[nng_mtx_lock(3supp)],
xref:nng.7.adoc[nng(7)]
