= nng_ipc_listener_listen(3ipc)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
// Copyright 2019 Devolutions <info@devolutions.net>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_ipc_listener_listen - bind IPC listener

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/supplemental/ipc/ipc.h>

int nng_ipc_listener_listen(nng_ipc_listener l, const nng_sockaddr *sa);
----

== DESCRIPTION

The `nng_ipc_listener_listen()` attempts to bind the listener _l_
to the local address specified by _sa_, which must be in the
`NNG_AF_IPC` address family and must have a valid IPC path.

== RETURN VALUES

This function returns 0 on success, and non-zero otherwise.

== ERRORS

[horizontal]
`NNG_EADDRINUSE`:: The address specified by _sa_ is already in use.
`NNG_EADDRINVAL`:: The address specified by _sa_ is invalid or unavailable.
`NNG_ECLOSED`:: The listener _l_ has been closed.
`NNG_EPERM`:: Insufficient permission to create the specified IPC path.
`NNG_ESTATE`:: The listener _l_ is already bound.

== SEE ALSO

[.text-left]
<<nng_strerror.3#,nng_strerror(3)>>,
<<nng_ipc_listener_accept.3ipc#,nng_ipc_listener_accept(3ipc)>>,
<<nng_ipc_listener_alloc.3ipc#,nng_ipc_listener_alloc(3ipc)>>,
<<nng_ipc_listener_close.3ipc#,nng_ipc_listener_close(3ipc)>>,
<<nng_ipc_listener_free.3ipc#,nng_ipc_listener_free(3ipc)>>,
<<nng_ipc_listener_getopt.3ipc#,nng_ipc_listener_getopt(3ipc)>>,
<<nng_sockaddr.5#,nng_sockaddr(5)>>,
<<nng_ipc_listener.5#,nng_ipc_listener(5)>>
