= nng_tls_dialer(5)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
// Copyright 2019 Devolutions <info@devolutions.net>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_tls_dialer - TLS dialer

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/supplemental/tls/tls.h>

typedef struct nng_tls_dialer_s nng_tls_dialer;
----

== DESCRIPTION

(((TLS, dialer)))
An `nng_tls_dialer` is a handle to a TLS "`dialer`", which is responsible for
creating connections (<<nng_tls.5#,`nng_tls`>> objects) by connecting to
remote systems.

NOTE: The `nng_tls_dialer` object is used for raw IPC connections, and
should not be confused with a dialer object created using the
<<nng_tls.7#,nng_tls(7)>> transport.

TIP: Most NNG applications should not use this, but instead use the
<<nng_tls.7#,nng_tls(7)>> transport instead.

== SEE ALSO

[.text-left]
<<nng_tls_dialer_alloc.3tls#,nng_tls_dialer_alloc(3tls)>>,
<<nng_tls_dialer_close.3tls#,nng_tls_dialer_close(3tls)>>,
<<nng_tls_dialer_dial.3tls#,nng_tls_dialer_dial(3tls)>>,
<<nng_tls_dialer_free.3tls#,nng_tls_dialer_free(3tls)>>,
<<nng_tls.5#,nng_tls(5)>>,
<<nng_tls_listener.5#,nng_tls_listener(5)>>,
<<nng_tls_options.5#,nng_tls_options(5)>>,
<<nng_tls.7#,nng_tls(7)>>
