= nng_http_server_get_tls(3http)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_http_server_get_tls - get HTTP server TLS configuration

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/supplemental/http/http.h>

int nng_http_server_get_tls(nng_http_server *s, nng_tls_config **cfgp);
----

== DESCRIPTION

The `nng_http_server_get_tls()` obtains the TLS configuration of server _s_ and
saves a pointer to it in the address referenced by _cfgp_.

The configuration will be `NULL` if the HTTP server instance is not enabled
to use HTTPS.

== RETURN VALUES

This function returns 0 on success, and non-zero otherwise.

== ERRORS

[horizontal]
`NNG_ENOMEM`:: Insufficient free memory exists.
`NNG_ENOTSUP`:: Either HTTP or TLS not supported.

== SEE ALSO

[.text-left]
<<nng_http_server_hold.3http#,nng_http_server_hold(3http)>>,
<<nng_http_server_set_tls.3http#,nng_http_server_set_tls(3http)>>,
<<nng_http_server_start.3http#,nng_http_server_start(3http)>>,
<<nng_tls_config_alloc.3tls#,nng_tls_config_alloc(3tls)>>,
<<nng_strerror.3#,nng_strerror(3)>>,
<<nng.7#,nng(7)>>
