= nng_pub(7)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_pub - publisher protocol

== SYNOPSIS

[source,c]
----
#include <nng/protocol/pubsub0/pub.h>
----

== DESCRIPTION

(((protocol, _pub_)))
The ((_pub_ protocol)) is one half of a ((publisher))/subscriber pattern.
In this pattern, a publisher sends data, which is broadcast to all
subscribers.
The subscribing applications only see the data to which
they have subscribed.

The _pub_ protocol is the publisher side, and the
xref:nng_sub.7.adoc[_sub_] protocol is the subscriber side.

NOTE: In this implementation, the publisher delivers all messages to all
subscribers.
The subscribers maintain their own subscriptions, and filter them locally.
Thus, this pattern should not be used in an attempt to reduce bandwidth
consumption.

The topics that subscribers subscribe to is just the first part of
the message body.
Applications should construct their messages accordingly.

=== Socket Operations

The xref:nng_pub_open.3.adoc[`nng_pub0_open()`] functions create a publisher socket.
This socket may be used to send messages, but is unable to receive them.
Attempts to receive messages will result in `NNG_ENOTSUP`.

=== Protocol Versions

Only version 0 of this protocol is supported.
(At the time of writing, no other versions of this protocol have been defined.)

=== Protocol Options

The _pub_ protocol has no protocol-specific options.

=== Protocol Headers

The _pub_ protocol has no protocol-specific headers.

== SEE ALSO

[.text-left]
xref:nng_pub_open.3.adoc[nng_pub_open(3)],
xref:nng_sub.7.adoc[nng_sub(7)],
xref:nng.7.adoc[nng(7)]
