= nng_http_set_method(3http)
//
// Copyright 2025 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_http_set_method - set HTTP request method

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/supplemental/http/http.h>

void nng_http_set_method(nng_http *conn, const char *method);
----

== DESCRIPTION

The `nng_http_set_method()` sets the HTTP method associated with
the connection _conn_ to _method_.  The _method_ must be a string,
such as "GET" or "POST".

The default value method for newly allocated requests is "GET".

If the method is longer than 32 bytes, it may be silently truncated.
(There are no methods defined that are this long.)

The value _method_ is copied, so the caller may dispose of it after
the call completes.

== SEE ALSO

[.text-left]
xref:nng_http_get_method.3http.adoc[nng_http_get_method(3http)],
xref:nng.7.adoc[nng(7)]
