= nng_aio_alloc(3)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_aio_alloc - allocate asynchronous I/O handle

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>

int nng_aio_alloc(nng_aio **aiop, void (*callb)(void *), void *arg);
----

== DESCRIPTION

The `nng_aio_alloc()` function allocates a handle for ((asynchronous I/O))
operations, and stores a pointer to it in __aiop__.
The handle is initialized with a completion ((callback)) of _callb_,
which will be executed when an associated asynchronous operation finishes.
It will be called with the argument _arg_.

NOTE: The callback _callb_ must not perform any blocking operations, and
must complete its execution quickly.  If _callb_ does block, this can
lead ultimately to an apparent "hang" or deadlock in the application.

Asynchronous I/O operations all take an xref:nng_aio.5.adoc[`nng_aio`]
handle such as allocated by this function.
Such operations are usually started by a function that returns immediately.
The operation is then run asynchronously, and completes sometime later.
When that operation is complete, the callback supplied here is called,
and that callback is able to determine the result of the operation using
xref:nng_aio_result.3.adoc[`nng_aio_result()`],
xref:nng_aio_count.3.adoc[`nng_aio_count()`],
and xref:nng_aio_get_output.3.adoc[`nng_aio_get_output()`].

It is possible to wait synchronously for an otherwise asynchronous operation
by using the function xref:nng_aio_wait.3.adoc[`nng_aio_wait()`].
In that case, it is permissible for _callb_ and _arg_ to both be `NULL`.
Note that if these are `NULL`, then it will not be possible to determine when the
operation is complete except by calling the aforementioned
xref:nng_aio_wait.3.adoc[`nng_aio_wait()`].

== RETURN VALUES

This function returns 0 on success, and non-zero otherwise.

== ERRORS

[horizontal]
`NNG_ENOMEM`:: Insufficient free memory to perform the operation.

== SEE ALSO

[.text-left]
xref:nng_aio_abort.3.adoc[nng_aio_abort(3)],
xref:nng_aio_cancel.3.adoc[nng_aio_cancel(3)],
xref:nng_aio_count.3.adoc[nng_aio_count(3)],
xref:nng_aio_free.3.adoc[nng_aio_free(3)],
xref:nng_aio_get_input.3.adoc[nng_aio_get_input(3)],
xref:nng_aio_get_msg.3.adoc[nng_aio_get_msg(3)],
xref:nng_aio_get_output.3.adoc[nng_aio_get_output(3)],
xref:nng_aio_result.3.adoc[nng_aio_result(3)],
xref:nng_aio_set_input.3.adoc[nng_aio_set_input(3)],
xref:nng_aio_set_iov.3.adoc[nng_aio_set_iov(3)],
xref:nng_aio_set_msg.3.adoc[nng_aio_set_msg(3)],
xref:nng_aio_set_timeout.3.adoc[nng_aio_set_timeout(3)],
xref:nng_aio_stop.3.adoc[nng_aio_stop(3)],
xref:nng_aio_wait.3.adoc[nng_aio_wait(3)],
xref:nng_strerror.3.adoc[nng_strerror(3)],
xref:nng_aio.5.adoc[nng_aio(5)],
xref:nng.7.adoc[nng(7)]
