= nng_ipc_dialer(5)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
// Copyright 2019 Devolutions <info@devolutions.net>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_ipc_dialer - IPC dialer

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/supplemental/ipc/ipc.h>

typedef struct nng_ipc_dialer_s nng_ipc_dialer;
----

== DESCRIPTION

(((IPC, dialer)))
An `nng_ipc_dialer` is a handle to an IPC "`dialer`", which is responsible for
creating a connections (<<nng_ipc.5#,`nng_ipc`>> objects) by connecting to
remote systems.

NOTE: The `nng_ipc_dialer` object is used for raw IPC connections, and
should not be confused with a dialer object created using the
<<nng_ipc.7#,nng_ipc(7)>> transport.

TIP: Most NNG applications should not use this, but instead use the
<<nng_ipc.7#,nng_ipc(7)>> transport instead.

== SEE ALSO

[.text-left]
<<nng_ipc_dialer_alloc.3ipc#,nng_ipc_dialer_alloc(3ipc)>>,
<<nng_ipc_dialer_close.3ipc#,nng_ipc_dialer_close(3ipc)>>,
<<nng_ipc_dialer_dial.3ipc#,nng_ipc_dialer_dial(3ipc)>>,
<<nng_ipc_dialer_free.3ipc#,nng_ipc_dialer_free(3ipc)>>,
<<nng_ipc.5#,nng_ipc(5)>>,
<<nng_ipc_listener.5#,nng_ipc_listener(5)>>,
<<nng_ipc.7#,nng_ipc(7)>>
