= nng_ipc_dialer_getopt(3ipc)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
// Copyright 2019 Devolutions <info@devolutions.net>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_ipc_dialer_getopt - get option from IPC dialer

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/supplemental/ipc/ipc.h>

int nng_ipc_getopt(nng_ipc_dialer *d, const char *name, void *data, size_t *sizep);
----

== DESCRIPTION

The `nng_ipc_dialer_getopt()` is used to retrieve the value of the option _name_ for the <<nng_ipc_dialer.5#,IPC dialer>> _d_.
The size of the buffer located at _data_ to receive the copy is passed by the
caller at the location referenced by _sizep_.
If this size is sufficient to hold the entire object, the object is copied into
the buffer specified by _data_.
In either event, the size of the source object (the amount of data copied,
or that would have been copied if sufficient space were available) is stored
at the location of _sizep_.

=== Options

There are no predefined options for IPC dialers at this time.

== RETURN VALUES

This function returns 0 on success, and non-zero otherwise.

== ERRORS

[horizontal]
`NNG_ECLOSED`:: The dialer is closed.
`NNG_EINVAL`:: There was insufficient space to receive the object.
	The amount of data actually needed is returned in _sizep_.
`NNG_ENOTSUP`:: The option _name_ is not supported.
`NNG_EWRITEONLY`:: The option _name_ may not read.

== SEE ALSO

[.text-left]
<<nng_ipc_dialer_setopt.3ipc#,nng_ipc_dialer_setopt(3ipc)>>,
<<nng_ipc_getopt.3ipc#,nng_ipc_getopt(3ipc)>>,
<<nng_options.5#,nng_options(5)>>,
<<nng_strerror.3#,nng_strerror(3)>>,
<<nng_ipc.5#,nng_ipc(5)>>,
<<nng_ipc_dialer.5#,nng_ipc_dialer(5)>>
