= nng_iov(5)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_iov - scatter/gather element

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>

typedef struct {
    void * iov_buf;
    size_t iov_len;
} nng_iov;
----

== DESCRIPTION

An `nng_iov` structure represents a single element in a ((scatter/gather))
array.
Some operations can use arrays of these to access different regions of
memory in a single operation.
For example, it may be useful to send a message with header data from
one part of memory, and a user payload from another.

The operations that do this typically store an array of these in
an xref:nng_aio.5.adoc[`nng_aio`] structure using the
xref:nng_aio_set_iov.3.adoc[`nng_aio_set_iov()`] function.

The following structure members are present:

`iov_buf`::
    This is a pointer to the first byte within the memory being
    referenced by this scatter/gather element.

`iov_len`::
    This is the size in bytes of this scatter/gather element.

== SEE ALSO

[.text-left]
xref:nng_aio_set_iov.3.adoc[nng_aio_set_iov(3)],
xref:nng_aio.5.adoc[nng_aio(5)],
xref:nng.7.adoc[nng(7)]
