= nng_http_conn_read_all(3http)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_http_conn_read_all - read all from HTTP connection

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/supplemental/http/http.h>

void nng_http_conn_read_all(nng_http_conn *conn, nng_aio *aio);
----

== DESCRIPTION

The `nng_http_conn_read_all()` function starts an asynchronous read from the
HTTP connection _conn_, into the scatter/gather vector located in the
asynchronous I/O structure _aio_.

NOTE: The xref:nng_aio_set_iov.3.adoc[`nng_aio_set_iov()`] function must have been
called first, to set the scatter/gather vector for _aio_.

This function returns immediately, with no return value.
Completion of the operation is signaled via the _aio_, and the final result
may be obtained via xref:nng_aio_result.3.adoc[`nng_aio_result()`].
That result will either be zero or an error code.

The I/O operation completes only when the entire amount of data
requested has been read, or an error has occurred.
If the operation
completes successfully, then the entire requested data has been read.

It is still possible for a partial read to complete in the event of an error.
The actual number of bytes read can be determined with
xref:nng_aio_count.3.adoc[`nng_aio_count()`].

TIP: The main purpose for this function is to facilitate reading HTTP
body content, after first determining the length of the body content
from the relevant HTTP headers (typically `Content-Length`).

== RETURN VALUES

None.

== ERRORS

[horizontal]
`NNG_ECANCELED`:: The operation was canceled.
`NNG_ECLOSED`:: The connection was closed.
`NNG_ECONNRESET`:: The peer closed the connection.
`NNG_EINVAL`:: The _aio_ does not contain a valid scatter/gather vector.
`NNG_ENOMEM`:: Insufficient free memory to perform the operation.
`NNG_ENOTSUP`:: HTTP operations are not supported.
`NNG_ETIMEDOUT`:: Timeout waiting for data from the connection.

== SEE ALSO

[.text-left]
xref:nng_aio_alloc.3.adoc[nng_aio_alloc(3)],
xref:nng_aio_count.3.adoc[nng_aio_count(3)],
xref:nng_aio_result.3.adoc[nng_aio_result(3)],
xref:nng_aio_set_iov.3.adoc[nng_aio_set_iov(3)],
xref:nng_strerror.3.adoc[nng_strerror(3)],
xref:nng_http_client_connect.3http.adoc[nng_http_client_connect(3)],
xref:nng_http_conn_read.3http.adoc[nng_http_conn_read(3)],
xref:nng.7.adoc[nng(7)]
