= nng_tcp_dialer_dial(3tcp)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_tcp_dialer_dial - initiate outgoing TCP connection

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/supplemental/tcp/tcp.h>

void nng_tcp_dialer_dial(nng_tcp_dialer *d, const nng_sockaddr *sa, nng_aio *aio);
----

== DESCRIPTION

The `nng_tcp_dialer_dial()` attempts to establish a TCP connection to the
remote peer identified by _sa_, using the dialer _d_.
The operation is completed asynchronously, using _aio_.

The address _sa_ must be in the `NNG_AF_INET` or `NNG_AF_INET6` families,
and have a valid IPv4 or IPv6 address and TCP port number.

If a connection is successfully established, the _aio_ will have the
resulting `<<nng_tcp.5#,nng_tcp>>` stored as its first output.
(See `<<nng_aio_get_output.3#,nng_aio_get_output()>>`.)

== RETURN VALUES

None.

== ERRORS

[horizontal]
`NNG_EADDRINVAL`:: The address specified is invalid.
`NNG_ECANCELED`:: The operation was aborted.
`NNG_ECLOSED`:: The dialer is closed.
`NNG_ECONNREFUSED`:: The TCP connection was refused by the server.
`NNG_ECONNRESET`:: The TCP connection was reset by the server.
`NNG_ENOMEM`:: Insufficient free memory exists.

== SEE ALSO

[.text-left]
<<nng_strerror.3#,nng_strerror(3)>>,
<<nng_tcp_dialer_alloc.3tcp#,nng_tcp_dialer_alloc(3tcp)>>,
<<nng_tcp_dialer_close.3tcp#,nng_tcp_dialer_close(3tcp)>>,
<<nng_tcp_dialer_free.3tcp#,nng_tcp_dialer_free(3tcp)>>,
<<nng_aio.5#,nng_aio(5)>>,
<<nng_sockaddr.5#,nng_sockaddr(5)>>,
<<nng_tcp.5#,nng_tcp(5)>>,
<<nng_tcp_dialer.5#,nng_tcp_dialer(5)>>
