= nng_http_conn_write(3http)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_http_conn_write - write to HTTP connection

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/supplemental/http/http.h>

void nng_http_conn_write(nng_http_conn *conn, nng_aio *aio);
----

== DESCRIPTION

The `nng_http_conn_write()` function starts an asynchronous write to the
HTTP connection _conn_ from the scatter/gather vector located in the
asynchronous I/O structure _aio_.

NOTE: The xref:nng_aio_set_iov.3.adoc[`nng_aio_set_iov()`] function must have been
called first, to set the scatter/gather vector for _aio_.

This function returns immediately, with no return value.
Completion of the operation is signaled via the _aio_, and the final
result may be obtained via xref:nng_aio_result.3.adoc[`nng_aio_result()`].
That result will either be zero or an error code.

The I/O operation completes as soon as at least one byte has been
written, or an error has occurred.
Therefore, the number of bytes written may be less than requested.
The actual number of bytes written can be determined with
xref:nng_aio_count.3.adoc[`nng_aio_count()`].

TIP: This function is intended to facilitate uses cases that involve changing
the protocol from HTTP, such as WebSocket.
Most applications will never need to use this function.

== RETURN VALUES

None.

== ERRORS

[horizontal]
`NNG_ECANCELED`:: The operation was canceled.
`NNG_ECLOSED`:: The connection was closed.
`NNG_ECONNRESET`:: The peer closed the connection.
`NNG_EINVAL`:: The _aio_ does not contain a valid scatter/gather vector.
`NNG_ENOMEM`:: Insufficient free memory to perform the operation.
`NNG_ENOTSUP`:: HTTP operations are not supported.
`NNG_ETIMEDOUT`:: Timeout waiting for data from the connection.

== SEE ALSO

[.text-left]
xref:nng_aio_alloc.3.adoc[nng_aio_alloc(3)],
xref:nng_aio_count.3.adoc[nng_aio_count(3)],
xref:nng_aio_result.3.adoc[nng_aio_result(3)],
xref:nng_aio_set_iov.3.adoc[nng_aio_set_iov(3)],
xref:nng_http_client_connect.3http.adoc[nng_http_client_connect(3http)],
xref:nng_http_conn_write_all.3http.adoc[nng_http_conn_write_all(3http)],
xref:nng_http_handler_alloc.3http.adoc[nng_http_handler_alloc(3http)],
xref:nng_strerror.3.adoc[nng_strerror(3)],
xref:nng.7.adoc[nng(7)]
