= nng_socket_set(3)
//
// Copyright 2024 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_socket_set - set socket option

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>

int nng_socket_set_bool(nng_socket s, const char *opt, bool bval);

int nng_socket_set_int(nng_socket s, const char *opt, int ival);

int nng_socket_set_ms(nng_socket s, const char *opt, nng_duration dur);

int nng_socket_set_size(nng_socket s, const char *opt, size_t z);

int nng_socket_set_uint64(nng_socket s, const char *opt, uint64_t u64);
----

== DESCRIPTION
(((options, socket)))
The `nng_socket_set` functions are used to configure options for
the socket _s_.
The actual options that may be configured in this way vary, and are
specified by _opt_.
A number of them are documented in xref:nng_options.5.adoc[nng_options(5)].

Protocol-specific options are documented with the protocol in question.

=== Forms

The details of the type, size, and semantics of the option will depend
on the actual option, and is documented with the option itself.

`nng_socket_set_bool()`::
This function is for options which take a Boolean (`bool`).
The _bval_ is passed to the option.

`nng_socket_set_int()`::
This function is for options which take an integer (`int`).
The _ival_ is passed to the option.

`nng_socket_set_ms()`::
This function is used to configure time durations (such as timeouts) using
type xref:nng_duration.5.adoc[`nng_duration`].
The duration _dur_ is an integer number of milliseconds.

`nng_socket_set_size()`::
This function is used to configure a size, _z_, typically for buffer sizes,
message maximum sizes, and similar options.

`nng_socket_set_uint64()`::
This function is used to configure a 64-bit unsigned value, _u64_.
This is typically used for options related to identifiers, network numbers,
and similar.

== RETURN VALUES

These functions return 0 on success, and non-zero otherwise.

== ERRORS

[horizontal]
`NNG_ECLOSED`:: Parameter _s_ does not refer to an open socket.
`NNG_EINVAL`:: The value being passed is invalid.
`NNG_ENOTSUP`:: The option _opt_ is not supported.
`NNG_EREADONLY`:: The option _opt_ is read-only.
`NNG_ESTATE`:: The socket is in an inappropriate state for setting this option.

== SEE ALSO

[.text-left]
xref:nng_socket_get.3.adoc[nng_socket_get(3)],
xref:nng_dialer_set.3.adoc[nng_dialer_set(3)],
xref:nng_listener_set.3.adoc[nng_listener_set(3)],
xref:nng_strerror.3.adoc[nng_strerror(3)],
xref:nng_options.5.adoc[nng_options(5)],
xref:nng_socket.5.adoc[nng_socket(5)],
xref:nng.7.adoc[nng(7)]
