= nng_msg_header_append(3)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_msg_header_append, nng_msg_header_append_u32 - append to message header

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>

int nng_msg_header_append(nng_msg *msg, const void *val, size_t size);

int nng_msg_header_append_u32(nng_msg *msg, uint32_t val32);
----

== DESCRIPTION

The `nng_msg_header_append()` and `nng_msg_header_append_u32()`
functions append data to
the end of the headers of message _msg_, reallocating it if necessary.
The first function appends _size_ bytes, copying them from _val_.
The second function appends the value _val32_ in network-byte order
(big-endian).


== RETURN VALUES

This function returns 0 on success, and non-zero otherwise.

== ERRORS

[horizontal]
`NNG_ENOMEM`:: Insufficient free memory exists.

== SEE ALSO

[.text-left]
<<nng_msg_alloc.3#,nng_msg_alloc(3)>>,
<<nng_msg_header.3#,nng_msg_header(3)>>,
<<nng_msg_header_chop.3#,nng_msg_header_chop(3)>>,
<<nng_msg_header_insert.3#,nng_msg_header_insert(3)>>,
<<nng_msg_header_len.3#,nng_msg_header_len(3)>>,
<<nng_msg_header_trim.3#,nng_msg_header_trim(3)>>,
<<nng_msg_free.3#,nng_msg_free(3)>>,
<<nng_strerror.3#,nng_strerror(3)>>,
<<nng.7#,nng(7)>>
