= nng_http_handler_set_tree(3http)

// Copyright 2025 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
// Copyright 2020 Dirac Research <robert.bielik@dirac.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.

== NAME

nng_http_handler_set_tree - set HTTP handler to match trees

== SYNOPSIS

[source,c]
----
#include <nng/nng.h>
#include <nng/http.h>

void nng_http_handler_set_tree(nng_http_handler *handler);
----

== DESCRIPTION

The `nng_http_handler_set_tree()` function causes the _handler_ to be matched if the request URI sent
by the client is a logical child of the path for _handler_, and no more specific
_handler_ has been registered.

This is useful in cases when the handler would like to examine the entire path
and possibly behave differently; for example a REST API that uses the rest of
the path to pass additional parameters.

TIP: This function is useful when constructing API handlers where a single
service address (path) supports dynamically generated children.
It can also provide a logical fallback instead of relying on a 404 error code.

== SEE ALSO

[.text-left]
xref:nng_http_handler_alloc.3http.adoc[nng_http_handler_alloc(3http)],
xref:nng_http_server_add_handler.3http.adoc[nng_http_server_add_handler(3http)],
xref:nng_http_get_method.3http.adoc[nng_http_get_method(3http)]
