= nng_ctx_setopt(3)
//
// Copyright 2019 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_ctx_setopt - set context option

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>

int nng_ctx_setopt(nng_ctx ctx, const char *opt, const void *val, size_t valsz);

int nng_ctx_setopt_bool(nng_ctx ctx, const char *opt, int bval);

int nng_ctx_setopt_int(nng_ctx ctx, const char *opt, int ival);

int nng_ctx_setopt_ms(nng_ctx ctx, const char *opt, nng_duration dur);

int nng_ctx_setopt_size(nng_ctx ctx, const char *opt, size_t z);

int nng_ctx_setopt_string(nng_ctx ctx, const char *opt, const char *str);

int nng_ctx_setopt_uint64(nng_ctx ctx, const char *opt, uint64_t u64);
----

== DESCRIPTION

NOTE: These functions are deprecated.  Please see xref:nng_ctx_set.3.adoc[nng_ctx_set].

(((options, context)))
The `nng_ctx_setopt()` functions are used to configure options for
the context _ctx_.
The actual options that may be configured in this way vary, and are
specified by _opt_.

NOTE: Context options are protocol specific.
The details will be documented with the protocol.

=== Forms

The details of the type, size, and semantics of the option will depend
on the actual option, and will be documented with the option itself.

`nng_ctx_setopt()`::
This function is untyped, and can be used to configure any arbitrary data.
The _val_ pointer addresses the data to copy, and _valsz_ is the
size of the objected located at _val_.

TIP: It may be easier to use one of the typed forms of this function.

`nng_ctx_setopt_bool()`::
This function is for options which take a Boolean (`bool`).
The _bval_ is passed to the option.

`nng_ctx_setopt_int()`::
This function is for options which take an integer (`int`).
The _ival_ is passed to the option.

`nng_ctx_setopt_ms()`::
This function is used to configure time durations (such as timeouts) using
type xref:nng_duration.5.adoc[`nng_duration`].
The duration _dur_ is an integer number of milliseconds.

`nng_ctx_setopt_size()`::
This function is used to configure a size, _z_, typically for buffer sizes,
message maximum sizes, and similar options.

`nng_ctx_setopt_string()`::
This function is used to pass configure a string, _str_.
Strings passed this way must be legal UTF-8 or ASCII strings, terminated
with a `NUL` (`\0`) byte.
(Other constraints may apply as well, see the documentation for each option
for details.)

`nng_ctx_setopt_uint64()`::
This function is used to configure a 64-bit unsigned value, _u64_.
This is typically used for options related to identifiers, network numbers,
and similar.

== RETURN VALUES

These functions return 0 on success, and non-zero otherwise.

== ERRORS

[horizontal]
`NNG_ECLOSED`:: Parameter _s_ does not refer to an open socket.
`NNG_EINVAL`:: The value being passed is invalid.
`NNG_ENOTSUP`:: The option _opt_ is not supported.
`NNG_EREADONLY`:: The option _opt_ is read-only.
`NNG_ESTATE`:: The socket is in an inappropriate state for setting this option.

== SEE ALSO

[.text-left]
xref:nng_ctx_getopt.3.adoc[nng_ctx_getopt(3)],
xref:nng_setopt.3.adoc[nng_setopt(3)],
xref:nng_strerror.3.adoc[nng_strerror(3)],
xref:nng_ctx.5.adoc[nng_ctx(5)],
xref:nng_options.5.adoc[nng_options(5)],
xref:nng_socket.5.adoc[nng_socket(5)],
xref:nng.7.adoc[nng(7)]
