= nng_ipc_listener(5)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
// Copyright 2019 Devolutions <info@devolutions.net>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_ipc_listener - IPC listener

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/supplemental/ipc/ipc.h>

typedef struct nng_ipc_dialer_s nng_ipc_dialer;
----

== DESCRIPTION

(((IPC, listener)))
An `nng_ipc_listener` is a handle to an IPC "`listener`", which is responsible
for accepting connections (<<nng_ipc.5#,`nng_ipc`>> objects) from remote
systems.

NOTE: The `nng_ipc_listener` object is used for raw IPC connections, and
should not be confused with a listener object created using the
<<nng_ipc.7#,nng_ipc(7)>> transport.

TIP: Most NNG applications should not use this, but instead use the
<<nng_ipc.7#,nng_ipc(7)>> transport instead.

== SEE ALSO

[.text-left]
<<nng_ipc_listener_accept.3ipc#,nng_ipc_listener_accept(3ipc)>>,
<<nng_ipc_listener_alloc.3ipc#,nng_ipc_listener_alloc(3ipc)>>,
<<nng_ipc_listener_close.3ipc#,nng_ipc_listener_close(3ipc)>>,
<<nng_ipc_listener_free.3ipc#,nng_ipc_listener_free(3ipc)>>,
<<nng_ipc_listener_listen.3ipc#,nng_ipc_listener_listen(3ipc)>>,
<<nng_ipc.5#,nng_ipc(5)>>,
<<nng_ipc_dialer.5#,nng_ipc_dialer(5)>>,
<<nng_ipc_options.5#,nng_ipc_options(5)>>,
<<nng_ipc.7#,nng_ipc(7)>>
