= nng_tls_config_hold(3tls)
//
// Copyright 2019 Staysail Systems, Inc. <info@staysail.tech>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_tls_config_hold - hold TLS configuration object

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/supplemental/tls/tls.h>

void nng_tls_config_alloc(nng_tls_config *cfg);
----

== DESCRIPTION

The `nng_tls_config_hold()` increments the reference count on
the configuration object named by _cfg_, thereby preventing it
from being freed while in use.

The hold can be released by calling
xref:nng_tls_config_free.3tls.adoc[`nng_tls_config_free()`].

Multiple holds can be placed on a configuration object; the object
will not be freed until the last hold is released.

== RETURN VALUES

None.

== ERRORS

None.

== SEE ALSO

[.text-left]
xref:nng_tls_config_alloc.3tls.adoc[nng_tls_config_alloc(3tls)],
xref:nng_tls_config_free.3tls.adoc[nng_tls_config_free(3tls)],
xref:nng.7.adoc[nng(7)]
