= nng_socket_get(3)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_socket_get - get socket option

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>

int nng_socket_get(nng_socket s, const char *opt, void *val, size_t *valszp);

int nng_socket_get_bool(nng_socket s, const char *opt, bool *bvalp);

int nng_socket_get_int(nng_socket s, const char *opt, int *ivalp);

int nng_socket_get_size(nng_socket s, const char *opt, size_t *zp);

int nng_socket_get_uint64(nng_socket s, const char *opt, uint64_t *u64p);

int nng_socket_get_string(nng_socket s, const char *opt, char **strp);

int nng_socket_get_ptr(nng_socket s, const char *opt, void **ptr);

int nng_socket_get_ms(nng_socket s, const char *opt, nng_duration *durp);

int nng_socket_get_addr(nng_socket s, const char *opt, nng_sockaddr *addrp);

----

== DESCRIPTION

(((options, socket)))
The `nng_socket_get()` functions are used to retrieve option values for
the xref:nng_socket.5.adoc[socket] _s_.
The actual options that may be retrieved in this way vary.
A number of them are documented in xref:nng_options.5.adoc[nng_options(5)].

Additionally transport-specific options and protocol-specific options are
documented with the transports and protocols themselves.

=== Forms

In all of these forms, the option _opt_ is retrieved from the socket _s_.
The forms vary based on the type of the option they take.

The details of the type, size, and semantics of the option will depend
on the actual option, and will be documented with the option itself.

`nng_socket_get()`::
This function is untyped and can be used to retrieve the value of any option.
The caller must store a pointer to a buffer to receive the value in _val_,
and the size of the buffer shall be stored at the location referenced by
_valszp_.
+
When the function returns, the actual size of the data copied (or that
would have been copied if sufficient space were present) is stored at
the location referenced by _valszp_.
If the caller's buffer is not large enough to hold the entire object,
then the copy is truncated.
Therefore the caller should check for truncation by verifying that the
returned size in _valszp_ does not exceed the original buffer size.
+
It is acceptable to pass `NULL` for _val_ if the value in _valszp_ is zero.
This can be used to determine the size of the buffer needed to receive
the object.
+
TIP: It may be easier to use one of the typed forms of this function.

`nng_socket_get_bool()`::
This function is for options which take a Boolean (`bool`).
The value will be stored at _bvalp_.

`nng_socket_get_int()`::
This function is for options which take an integer (`int`).
The value will be stored at _ivalp_.

`nng_socket_get_ms()`::
This function is used to retrieve time xref:nng_duration.5.adoc[durations]
(such as timeouts), stored in _durp_ as a number of milliseconds.
(The special value ((`NNG_DUR_INFINITE`)) means an infinite amount of time, and
the special value ((`NNG_DUR_DEFAULT`)) means a context-specific default.)

`nng_socket_get_ptr()`::
This function is used to retrieve a pointer, _ptr_, to structured data.
The data referenced by _ptr_ is generally managed using other functions.
Note that this form is somewhat special in that the object is generally
not copied, but instead the *pointer* to the object is copied.

`nng_socket_get_size()`::
This function is used to retrieve a size into the pointer _zp_,
typically for buffer sizes, message maximum sizes, and similar options.

`nng_socket_get_string()`::
This function is used to retrieve a string into _strp_.
This string is created from the source using xref:nng_strdup.3.adoc[`nng_strdup()`]
and consequently must be freed by the caller using
xref:nng_strfree.3.adoc[`nng_strfree()`] when it is no longer needed.

`nng_socket_get_uint64()`::
This function is used to retrieve a 64-bit unsigned value into the value
referenced by _u64p_.
This is typically used for options related to identifiers, network
numbers, and similar.

== RETURN VALUES

These functions return 0 on success, and non-zero otherwise.

== ERRORS

[horizontal]
`NNG_EBADTYPE`:: Incorrect type for option.
`NNG_ECLOSED`:: Parameter _s_ does not refer to an open socket.
`NNG_EINVAL`:: Size of destination _val_ too small for object.
`NNG_ENOMEM`:: Insufficient memory exists.
`NNG_ENOTSUP`:: The option _opt_ is not supported.
`NNG_EWRITEONLY`:: The option _opt_ is write-only.

== SEE ALSO

[.text-left]
xref:nng_dialer_get.3.adoc[nng_dialer_get(3)],
xref:nng_listener_get.3.adoc[nng_listener_get(3)],
xref:nng_pipe_get.3.adoc[nng_pipe_get(3)],
xref:nng_socket_set.3.adoc[nng_socket_set(3)],
xref:nng_strdup.3.adoc[nng_strdup(3)],
xref:nng_strerror.3.adoc[nng_strerror(3)],
xref:nng_strfree.3.adoc[nng_strfree(3)],
xref:nng_duration.5.adoc[nng_duration(5)],
xref:nng_options.5.adoc[nng_options(5)],
xref:nng_socket.5.adoc[nng_socket(5)],
xref:nng.7.adoc[nng(7)]
