= nng_ipc_dialer_dial(3ipc)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
// Copyright 2019 Devolutions <info@devolutions.net>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_ipc_dialer_dial - initiate outgoing IPC connection

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/supplemental/ipc/ipc.h>

void nng_ipc_dialer_dial(nng_ipc_dialer *d, const nng_sockaddr *sa, nng_aio *aio);
----

== DESCRIPTION

The `nng_ipc_dialer_dial()` attempts to establish an IPC connection to the
remote peer identified by _sa_, using the dialer _d_.
The operation is completed asynchronously, using _aio_.

The address _sa_ must be in the `NNG_AF_IPC` family,
and have a valid path for IPC.

If a connection is successfully established, the _aio_ will have the
resulting <<nng_ipc.5#,`nng_ipc`>> stored as its first output.
(See <<nng_aio_get_output.3#,`nng_aio_get_output()`>>.)

== RETURN VALUES

None.

== ERRORS

[horizontal]
`NNG_EADDRINVAL`:: The address specified is invalid.
`NNG_ECANCELED`:: The operation was aborted.
`NNG_ECLOSED`:: The dialer is closed.
`NNG_ECONNREFUSED`:: The IPC connection was refused by the server.
`NNG_ECONNRESET`:: The IPC connection was reset by the server.
`NNG_ENOMEM`:: Insufficient free memory exists.
`NNG_EPERM`:: Insufficient permission to access the IPC path.

== SEE ALSO

[.text-left]
<<nng_strerror.3#,nng_strerror(3)>>,
<<nng_ipc_dialer_alloc.3ipc#,nng_ipc_dialer_alloc(3ipc)>>,
<<nng_ipc_dialer_close.3ipc#,nng_ipc_dialer_close(3ipc)>>,
<<nng_ipc_dialer_free.3ipc#,nng_ipc_dialer_free(3ipc)>>,
<<nng_aio.5#,nng_aio(5)>>,
<<nng_sockaddr.5#,nng_sockaddr(5)>>,
<<nng_ipc.5#,nng_ipc(5)>>,
<<nng_ipc_dialer.5#,nng_ipc_dialer(5)>>
