= nng_tls_listener_listen(3tls)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
// Copyright 2019 Devolutions <info@devolutions.net>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_tls_listener_listen - bind listener to TLS port

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/supplemental/tls/tls.h>

int nng_tls_listener_listen(nng_tls_listener l, const nng_sockaddr *sa);
----

== DESCRIPTION

The `nng_tls_listener_listen()` attempts to bind the listener _l_
to the local address specified by _sa_, which must be in the
`NNG_AF_INET` or `NNG_AF_INET6` address family.

This also sets the underlying port into passive mode, ready to
accept an incoming connection, and established a listen queue
for receiving incoming connections.  (The queue depth is system
specific, but typically 128.)

The actual IPv4 or IPv6 address in _sa_ may refer either to a locally
configured interface address, or to a zero-valued adddress to indicate
that all interfaces on the system should be bound.

The TCP port number may also be zero.  In this case the system will
choose a free TCP port at random, and use it.

The chosen port number may be retrieved using the
<<nng_options.5#,`NNG_OPT_LOCADDR`>> option with the
<<nng_tls_listener_getopt.3tls#,`nng_tls_listener_getopt()`>> function.

== RETURN VALUES

This function returns 0 on success, and non-zero otherwise.

== ERRORS

[horizontal]
`NNG_EADDRINUSE`:: The address specified by _sa_ is already in use.
`NNG_EADDRINVAL`:: The address specified by _sa_ is invalid or unavailable.
`NNG_ECLOSED`:: The listener _l_ has been closed.
`NNG_ECRYPTO`:: Cryptographic or certificate error.
`NNG_ESTATE`:: The listener _l_ is already bound.

== SEE ALSO

[.text-left]
<<nng_strerror.3#,nng_strerror(3)>>,
<<nng_tls_listener_accept.3tls#,nng_tls_listener_accept(3tls)>>,
<<nng_tls_listener_alloc.3tls#,nng_tls_listener_alloc(3tls)>>,
<<nng_tls_listener_close.3tls#,nng_tls_listener_close(3tls)>>,
<<nng_tls_listener_free.3tls#,nng_tls_listener_free(3tls)>>,
<<nng_tls_listener_getopt.3tls#,nng_tls_listener_getopt(3tls)>>,
<<nng_options.5#,nng_options(5)>>,
<<nng_sockaddr.5#,nng_sockaddr(5)>>,
<<nng_tls_listener.5#,nng_tls_listener(5)>>
