= nng_tcp_setopt(3tcp)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
// Copyright 2019 Devolutions <info@devolutions.net>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_tcp_setopt - set option on TCP connection

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>
#include <nng/supplemental/tcp/tcp.h>

int nng_tcp_setopt(nng_tcp *conn, const char *name, const void *data, size_t size);
----

== DESCRIPTION

The `nng_tcp_setopt()` is used to set the option _name_ for the
<<nng_tcp.5#,TCP connection>> _conn_.
The value to set is copied from _data_, which should be _size_ bytes
in length.

=== Options

The options specifically suppported for modification on TCP
connections are:

* <<nng_options.5#NNG_OPT_TCP_KEEPALIVE,`NNG_OPT_TCP_KEEPALIVE`>>
* <<nng_options.5#NNG_OPT_TCP_NODELAY,`NNG_OPT_TCP_NODELAY`>>

== RETURN VALUES

This function returns 0 on success, and non-zero otherwise.

== ERRORS

[horizontal]
`NNG_ECLOSED`:: The connection _conn_ is closed.
`NNG_EINVAL`:: Either _data_ or _size_ are invalid.
`NNG_ENOTSUP`:: The option _name_ is not supported.
`NNG_EREADONLY`:: The option _name_ may not be modified.

== SEE ALSO

[.text-left]
<<nng_tcp_getopt.3tcp#,nng_tcp_getopt(3tcp)>>,
<<nng_options.5#,nng_options(5)>>,
<<nng_strerror.3#,nng_strerror(3)>>,
<<nng_tcp.5#,nng_tcp(5)>>
