= nng_http_server_release(3)
:copyright: Copyright 2018 mailto:info@staysail.tech[Staysail Systems, Inc.] + \
            Copyright 2018 mailto:info@capitar.com[Capitar IT Group BV] + \
            {blank} + \
            This document is supplied under the terms of the \
            https://opensource.org/licenses/MIT[MIT License].

== NAME

nng_http_server_release - release HTTP server instance

== SYNOPSIS

[source, c]
-----------
#include <nng/nng.h>
#include <nng/supplemental/http/http.h>

void nng_http_server_release(nng_http_server *server);
-----------


== DESCRIPTION

The `nng_http_server_release()` releases an instance of an HTTP _server_
that was previously held with
<<nng_http_server_hold#,nng_http_server_hold(3)>>.

This effectively drops the reference count on the server instance.  When
the reference count drops to zero, then the _server_ and all resources
associated with it (e.g. HTTP handlers, connections, etc.) are deallocated.
(If the server is "running" when this occurs, then the server is stopped.)

WARNING: It is an error to release an instance of a server that has
not previously been held, or to attempt to release an instance more
times than it has been held.

== RETURN VALUES

None.

== ERRORS

None.

== SEE ALSO

<<nng_http_server_hold#,nng_http_server_hold(3)>>,
<<nng_http_server_stop#,nng_http_server_stop(3)>>,
<<nng#,nng(7)>>

== COPYRIGHT

{copyright}
