= nng_aio_get_output(3)
:copyright: Copyright 2018 mailto:info@staysail.tech[Staysail Systems, Inc.] + \
            Copyright 2018 mailto:info@capitar.com[Capitar IT Group BV] + \
            {blank} + \
            This document is supplied under the terms of the \
            https://opensource.org/licenses/MIT[MIT License].

== NAME

nng_aio_get_output - return output result

== SYNOPSIS

[source, c]
-----------
#include <nng/nng.h>

void *nng_aio_get_output(nng_aio *aio, unsigned int index);
-----------

== DESCRIPTION

The `nng_aio_get_output()` function returns the output result at _index_
resulting from the asynchronous operation associated with _aio_.

The type and semantics of output parameters are determined by specific
operations.

NOTE: If the _index_ does not correspond to a defined output for the operation,
or the operation did not succeed, then the return value will be `NULL`.

CAUTION: It is an error to call this function while the _aio_ is currently
in use by an active asynchronous operation, or if no operation has been
performed using the _aio_ yet.

== RETURN VALUES

The __index__th result of the operation, or `NULL`.

== ERRORS

None.

== SEE ALSO

<<nng_aio_alloc#,nng_aio_alloc(3)>>,
<<nng_aio_get_output#,nng_aio_get_output(3)>>,
<<nng_aio_set_input#,nng_aio_set_input(3)>>,
<<nng_aio_result#,nng_aio_result(3)>>,
<<nng#,nng(7)>>

== COPYRIGHT

{copyright}
