= nng_msg_header_chop(3)
:doctype: manpage
:manmanual: nng
:mansource: nng
:manvolnum: 3
:copyright: Copyright 2018 Staysail Systems, Inc. <info@staysail.tech> \
            Copyright 2018 Capitar IT Group BV <info@capitar.com> \
            This software is supplied under the terms of the MIT License, a \
            copy of which should be located in the distribution where this \
            file was obtained (LICENSE.txt).  A copy of the license may also \
            be found online at https://opensource.org/licenses/MIT.

== NAME

nng_msg_header_chop, nng_msg_header_chop_u32 - remove data from end of message header

== SYNOPSIS

[source, c]
-----------
#include <nng/nng.h>

int nng_msg_header_chop(nng_msg *msg, size_t size);
int nng_msg_header_chop_u32(nng_msg *msg, uint32_t *val32);
-----------

== DESCRIPTION

The `nng_msg_header_chop()` and `nng_msg_header_chop_u32()` functions remove
data from the end of the header of message _msg_. 
The first function removes _size_ bytes.
The second function removes 4 bytes, and stores them in the value _val32_,
after converting them from network-byte order (big-endian) to native
byte order.

== RETURN VALUES

This function returns 0 on success, and non-zero otherwise.

== ERRORS

`NNG_EINVAL`:: The message header is too short to remove the requested data.

== SEE ALSO

<<nng_msg_alloc#,nng_msg_alloc(3)>>,
<<nng_msg_header#,nng_msg_header(3)>>,
<<nng_msg_header_append#,nng_msg_header_append(3)>>,
<<nng_msg_header_insert#,nng_msg_header_insert(3)>>,
<<nng_msg_header_len#,nng_msg_header_len(3)>>,
<<nng_msg_header_trim#,nng_msg_header_trim(3)>>,
<<nng_msg_free#,nng_msg_free(3)>>,
<<nng_strerror#,nng_strerror(3)>>,
<<nng#,nng(7)>>

== COPYRIGHT

Copyright 2018 mailto:info@staysail.tech[Staysail Systems, Inc.] +
Copyright 2018 mailto:info@capitar.com[Capitar IT Group BV]

This document is supplied under the terms of the
https://opensource.org/licenses/MIT[MIT License].
