= nng_msg_body(3)
:doctype: manpage
:manmanual: nng
:mansource: nng
:manvolnum: 3
:copyright: Copyright 2018 Staysail Systems, Inc. <info@staysail.tech> \
            Copyright 2018 Capitar IT Group BV <info@capitar.com> \
            This software is supplied under the terms of the MIT License, a \
            copy of which should be located in the distribution where this \
            file was obtained (LICENSE.txt).  A copy of the license may also \
            be found online at https://opensource.org/licenses/MIT.

== NAME

nng_msg_body - return message body

== SYNOPSIS

[source, c]
-----------
#include <nng/nng.h>

void *nng_msg_body(nng_msg *msg);
-----------

== DESCRIPTION

The `nng_msg_body()` function returns a pointer to the start of the body
content of the message _msg_.

NOTE: The value returned by this is invalidated by a call to any of the
functions that modify the message itself.  Such functions are
<<nng_msg_free#,nng_msg_free(3)>>, <<nng_msg_realloc#,nng_msg_realloc(3)>>,
any of the <<nng_msg_trim#,nng_msg_trim(3)>>, 
<<nng_msg_chop#,nng_msg_chop(3)>>, <<nng_msg_append#,nng_msg_append(3)>>, 
or <<nng_msg_insert#,nng_msg_insert(3)>> variants.


== RETURN VALUES

Pointer to start of message body.

== ERRORS

None.

== SEE ALSO

<<nng_msg_alloc#,nng_msg_alloc(3)>>,
<<nng_msg_append#,nng_msg_append(3)>>,
<<nng_msg_chop#,nng_msg_chop(3)>>,
<<nng_msg_free#,nng_msg_free(3)>>,
<<nng_msg_insert#,nng_msg_insert(3)>>,
<<nng_msg_len#,nng_msg_len(3)>>,
<<nng_msg_realloc#,nng_msg_realloc(3)>>,
<<nng_msg_trim#,nng_msg_trim(3)>>,
<<nng#,nng(7)>>


== COPYRIGHT

Copyright 2018 mailto:info@staysail.tech[Staysail Systems, Inc.] +
Copyright 2018 mailto:info@capitar.com[Capitar IT Group BV]

This document is supplied under the terms of the
https://opensource.org/licenses/MIT[MIT License].
