= nng_msg_header(3)
:doctype: manpage
:manmanual: nng
:mansource: nng
:manvolnum: 3
:copyright: Copyright 2018 Staysail Systems, Inc. <info@staysail.tech> \
            Copyright 2018 Capitar IT Group BV <info@capitar.com> \
            This software is supplied under the terms of the MIT License, a \
            copy of which should be located in the distribution where this \
            file was obtained (LICENSE.txt).  A copy of the license may also \
            be found online at https://opensource.org/licenses/MIT.

== NAME

nng_msg_header - return message header

== SYNOPSIS

[source, c]
-----------
#include <nng/nng.h>

void *nng_msg_header(nng_msg *msg);
-----------

== DESCRIPTION

The `nng_msg_header()` function returns a pointer to the start of the header
content of the message _msg_.

NOTE: The message header contains protocol-specific header content.  Most
applications should not need to access this content, but it is available
for raw mode sockets (set with the `NNG_OPT_RAW` option -- see
<<nng_setopt#,nng_setopt(3)>> for more details.)

NOTE: The value returned by this is invalidated by a call to any of the
functions that modify the message or the header content.

== RETURN VALUES

Pointer to start of message header.

== ERRORS

None.

== SEE ALSO

<<nng_msg_alloc#,nng_msg_alloc(3)>>,
<<nng_msg_body#,nng_msg_body(3)>>,
<<nng_msg_free#,nng_msg_free(3)>>,
<<nng_msg_header_append#,nng_msg_header_append(3)>>,
<<nng_msg_header_chop#,nng_msg_header_chop(3)>>,
<<nng_msg_header_insert#,nng_msg_header_insert(3)>>
<<nng_msg_header_len#,nng_msg_header_len(3)>>,
<<nng_msg_header_trim#,nng_msg_header_trim(3)>>,
<<nng#,nng(7)>>

== COPYRIGHT

Copyright 2018 mailto:info@staysail.tech[Staysail Systems, Inc.] +
Copyright 2018 mailto:info@capitar.com[Capitar IT Group BV]

This document is supplied under the terms of the
https://opensource.org/licenses/MIT[MIT License].
