= nng_http_res_set_header(3)
:doctype: manpage
:manmanual: nng
:mansource: nng
:manvolnum: 3
:copyright: Copyright 2018 Staysail Systems, Inc. <info@staysail.tech> \
            Copyright 2018 Capitar IT Group BV <info@capitar.com> \
            This software is supplied under the terms of the MIT License, a \
            copy of which should be located in the distribution where this \
            file was obtained (LICENSE.txt).  A copy of the license may also \
            be found online at https://opensource.org/licenses/MIT.

== NAME

nng_http_res_set_header - set HTTP response header

== SYNOPSIS

[source, c]
-----------
#include <nng/nng.h>

int nng_http_res_set_header(nng_http_res *res, const char *key);

-----------

== DESCRIPTION

The `nng_http_res_del_header()` removes all HTTP headers with the
associated _key_ from the response structure _res_.

The value of _key_ is case insensitive, and should not include the final
colon in an HTTP header.  For example, specifying `Host` or `hOSt` are
equivalent, whereas the value `Host:` is not a legal header key.

== RETURN VALUES

This function returns 0 on success, and non-zero otherwise.

== ERRORS

`NNG_ENOENT`:: No header with the key _key_ was present.
`NNG_ENOTSUP`:: No support for HTTP in the library.

== SEE ALSO

<<nng_http_res_alloc#,nng_http_res_alloc(3)>>,
<<nng_http_res_add_header#,nng_http_res_add_header(3)>>,
<<nng_http_res_del_header#,nng_http_res_del_header(3)>>,
<<nng_http_res_get_header#,nng_http_res_get_header(3)>>,
<<nng#,nng(7)>>


== COPYRIGHT

Copyright 2018 mailto:info@staysail.tech[Staysail Systems, Inc.] +
Copyright 2018 mailto:info@capitar.com[Capitar IT Group BV]

This document is supplied under the terms of the
https://opensource.org/licenses/MIT[MIT License].
