= nng_dialer_close(3)
:doctype: manpage
:manmanual: nng
:mansource: nng
:manvolnum: 3
:copyright: Copyright 2018 mailto:info@staysail.tech[Staysail Systems, Inc.] + \
            Copyright 2018 mailto:info@capitar.com[Capitar IT Group BV] + \
            {blank} + \
            This document is supplied under the terms of the \
            https://opensource.org/licenses/MIT[MIT License].

== NAME

nng_listener_close - close listener

== SYNOPSIS

[source, c]
-----------
#include <nng/nng.h>

int nng_dialer_close(nng_dialer d);
-----------

== DESCRIPTION

The `nng_dialer_close()` function closes the listener _d_.
This also closes any pipe that has been created by the dialer.

Once this function returns, the dialer _d_ and any of its resources
are deallocated.  Therefore it is an error to attempt to access _d_
after this function has returned.  (Attempts to do so will result in
`NNG_ECLOSED` errors.)

Dialers are implicitly closed when the socket they are associated with
is closed.

== RETURN VALUES

This function returns 0 on success, and non-zero otherwise.

== ERRORS

`NNG_ECLOSED`:: Parameter _d_ does not refer to an open listener.

== SEE ALSO

<<nng_close#,nng_close(3)>>,
<<nng_dial#,nng_dial(3)>>,
<<nng_dialer_create#,nng_dialer_create(3)>>
<<nng_strerror#,nng_strerror(3)>>,
<<nng#,nng(7)>>

== COPYRIGHT

{copyright}