= nng_listener_create(3)
:doctype: manpage
:manmanual: nng
:mansource: nng
:manvolnum: 3
:copyright: Copyright 2018 mailto:info@staysail.tech[Staysail Systems, Inc.] + \
            Copyright 2018 mailto:info@capitar.com[Capitar IT Group BV] + \
            {blank} + \
            This document is supplied under the terms of the \
            https://opensource.org/licenses/MIT[MIT License].

== NAME

nng_listener_create - create listener

== SYNOPSIS

[source, c]
-----------
#include <nng/nng.h>

int nng_listener_create(nng_listener *listenerp, nng_socket s, const char *url);
-----------

== DESCRIPTION

The `nng_listener_create()` function creates a newly initialized
listener, associated with socket _s_, and configured to listen at the
address specified by _url_, and stores a pointer to at the location
referenced by _listenerp_.

Listeners are used to accept connections initiated by remote dialers.  An
incoming connection generally results in a pipe being created and attached
to the socket _s_.  Unlike dialers, listeners generally can create many
pipes, which may be open concurrently.

TIP: While it is convenient to think of listeners as "servers", the relationship
between the listener or dialer is orthogonal to any server or client status
that might be associated with a given protocol.  For example, a <<nng_req#,REQ>>
socket might have associated dialers, but might also have associated listeners.
It may even have some of each at the same time!

The listener is not started, but may be further configured with
the <<nng_listener_setopt#,nng_listener_setopt(3)>> family of
functions.

Once it is fully configured, the listener may be started using the
<<nng_listener_start#,nng_listener_start(3)>> function.

TIP: If no specific configuration is required, consider using the
simpler <<nng_listen#,nng_listen(3)>> function instead.

== RETURN VALUES

This function returns 0 on success, and non-zero otherwise.

== ERRORS

`NNG_EADDRINVAL`:: An invalid _url_ was specified.
`NNG_ECLOSED`:: The socket _s_ is not open.
`NNG_ENOMEM`:: Insufficient memory is available.

== SEE ALSO

<<nng_strerror#,nng_strerror(3)>>,
<<nng_dialer_create#,nng_dialer_create(3)>>
<<nng_listen#,nng_listen(3)>>,
<<nng_listener_close#,nng_listener_close(3)>>,
<<nng_listener_getopt#,nng_listener_getopt(3)>>,
<<nng_listener_setopt#,nng_listener_setopt(3)>>,
<<nng_listener_start#,nng_listener_start(3)>>,
<<nng#,nng(7)>>

== COPYRIGHT

{copyright}
