= nng_http_res_set_header(3)
:doctype: manpage
:manmanual: nng
:mansource: nng
:manvolnum: 3
:copyright: Copyright 2018 mailto:info@staysail.tech[Staysail Systems, Inc.] + \
            Copyright 2018 mailto:info@capitar.com[Capitar IT Group BV] + \
            {blank} + \
            This document is supplied under the terms of the \
            https://opensource.org/licenses/MIT[MIT License].

== NAME

nng_http_res_set_header - set HTTP response header

== SYNOPSIS

[source, c]
-----------
#include <nng/nng.h>
#include <nng/supplemental/http/http.h>

int nng_http_res_set_header(nng_http_res *res, const char *key,
    const char *val);
-----------

== DESCRIPTION

The `nng_http_res_set_header()` sets the HTTP header for the response
_res_ and the _key_ to the _val_.  The _key_ and _val_ are copied.
Any previous header with the same _key_ is replaced.

TIP: See <<nng_http_res_add_header#,nng_http_res_add_header(3)>> to
add additional headers with the same _key_ without replacing them.

The value of _key_ is case insensitive, and should not include the final
colon in an HTTP header.  For example, specifying `Host` or `hOSt` are
equivalent, whereas the value `Host:` is not a legal header key.

== RETURN VALUES

This function returns 0 on success, and non-zero otherwise.

== ERRORS

`NNG_ENOMEM`:: Insufficient memory to perform the operation.
`NNG_ENOTSUP`:: No support for HTTP in the library.

== SEE ALSO

<<nng_http_res_alloc#,nng_http_res_alloc(3)>>,
<<nng_http_res_add_header#,nng_http_res_add_header(3)>>,
<<nng_http_res_del_header#,nng_http_res_del_header(3)>>,
<<nng_http_res_get_header#,nng_http_res_get_header(3)>>,
<<nng#,nng(7)>>

== COPYRIGHT

{copyright}