= nng_http_res_set_reason(3)
:doctype: manpage
:manmanual: nng
:mansource: nng
:manvolnum: 3
:copyright: Copyright 2018 mailto:info@staysail.tech[Staysail Systems, Inc.] + \
            Copyright 2018 mailto:info@capitar.com[Capitar IT Group BV] + \
            {blank} + \
            This document is supplied under the terms of the \
            https://opensource.org/licenses/MIT[MIT License].

== NAME

nng_http_res_set_reason - set HTTP response reason

== SYNOPSIS

[source, c]
-----------
#include <nng/nng.h>
#include <nng/supplemental/http/http.h>

int nng_http_res_set_reason(nng_http_res *res, const char *reason);
-----------

== DESCRIPTION

The `nng_http_res_set_reason()` sets the human readable "reason phrase"
associated with the response _res_ to _reason_. 

If the value of _reason_ is `NULL` (the default), then a default reason
phrase is supplied based upon the value of the status code (see
<<nng_http_res_set_status#,nng_http_res_set_status(3)>>).

TIP: The _reason_ is never parsed automatically, but it can be a hint for humans
     to help them understand the nature of any erroroneous result.

A local copy of the _reason_ is made in the response _res_.

== RETURN VALUES

This function returns 0 on success, and non-zero otherwise.

== ERRORS

`NNG_ENOMEM`:: Insufficient memory to perform the operation.
`NNG_ENOTSUP`:: No support for HTTP in the library.

== SEE ALSO

<<nng_http_res_alloc#,nng_http_res_alloc(3)>>,
<<nng_http_res_get_reason#,nng_http_req_get_reason(3)>>,
<<nng_http_res_set_status#,nng_http_req_set_status(3)>>,
<<nng#,nng(7)>>


== COPYRIGHT

{copyright}