= nng_aio_result(3)
:copyright: Copyright 2018 mailto:info@staysail.tech[Staysail Systems, Inc.] + \
            Copyright 2018 mailto:info@capitar.com[Capitar IT Group BV] + \
            {blank} + \
            This document is supplied under the terms of the \
            https://opensource.org/licenses/MIT[MIT License].

== NAME

nng_aio_result - return result of asynchronous operation

== SYNOPSIS

[source, c]
-----------
#include <nng/nng.h>

int nng_aio_wait(nng_aio *aio);
-----------


== DESCRIPTION

The `nng_aio_result()` returns the result of the operation associated
with the handle _aio_.
If the operation was successful, then 0 is returned.  Otherwise a non-zero
error code is returned.

NOTE: The return value from this function is undefined if the operation
has not completed yet.   Either call this from the handle's completion
callback, or after waiting for the operation to complete with
<<nng_aio_wait#,nng_aio_wait(3)>>.

== RETURN VALUES

The result of the operation, either zero on success, or an error 
number on failure.

== ERRORS

`NNG_ETIMEDOUT`:: The operation timed out.
`NNG_ECANCELED`:: The operation was canceled.

Various other return values are possible dependending on the operation.

== SEE ALSO

<<nng_aio_abort#,nng_aio_abort(3)>>,
<<nng_aio_alloc#,nng_aio_alloc(3)>>,
<<nng_aio_wait#,nng_aio_wait(3)>>,
<<nng_strerror#,nng_strerror(3)>>,
<<nng#,nng(7)>>

== COPYRIGHT

{copyright}
