= nng_http_res_set_data(3)
:doctype: manpage
:manmanual: nng
:mansource: nng
:manvolnum: 3
:copyright: Copyright 2018 mailto:info@staysail.tech[Staysail Systems, Inc.] + \
            Copyright 2018 mailto:info@capitar.com[Capitar IT Group BV] + \
            {blank} + \
            This document is supplied under the terms of the \
            https://opensource.org/licenses/MIT[MIT License].

== NAME

nng_http_res_set_data - set HTTP response body

== SYNOPSIS

[source, c]
-----------
#include <nng/nng.h>

int nng_http_res_set_data(nng_http_res *res, const void *body, size_t size);
-----------

== DESCRIPTION

The `nng_http_res_set_data()` sets the HTTP body associated with
the response _res_ to _body_, and the size of the body to _size_.
This body data will be automatically sent with the response when it
is sent using <<nng_http_conn_write_res#,nni_http_conn_write_res(3)>>.

This also updates the relevant `Content-Length` header of _res_.

NOTE: The current framework does not support sending data via chunked
transfer-encoding.

The _body_ is *not* copied, and the caller must ensure that it is available
until the _res_ is deallocated.

TIP: To have a local copy allocated with _res_ that will be automatically
deallocated when _res_ is freed,
see <<nng_http_res_copy_data#,nng_http_res_copy_data(3)>>.

TIP: It is a good idea to also set the `Content-Type` header.

== RETURN VALUES

This function returns 0 on success, and non-zero otherwise.

== ERRORS

`NNG_ENOMEM`:: Insufficient memory to perform the operation.
`NNG_ENOTSUP`:: No support for HTTP in the library.

== SEE ALSO

<<nng_http_conn_write_res#,nng_http_conn_write_res(3)>>,
<<nng_http_res_alloc#,nng_http_res_alloc(3)>>,
<<nng_http_res_copy_data#,nng_http_res_copy_data(3)>>,
<<nng_http_res_set_header#,nng_http_res_set_header(3)>>,
<<nng#,nng(7)>>

== COPYRIGHT

{copyright}