= nng_http_client_set_tls(3)
:doctype: manpage
:manmanual: nng
:mansource: nng
:manvolnum: 3
:copyright: Copyright 2018 mailto:info@staysail.tech[Staysail Systems, Inc.] + \
            Copyright 2018 mailto:info@capitar.com[Capitar IT Group BV] + \
            {blank} + \
            This document is supplied under the terms of the \
            https://opensource.org/licenses/MIT[MIT License].

== NAME

nng_http_client_set_tls - set HTTP client TLS configuration

== SYNOPSIS

[source, c]
-----------
#include <nng/nng.h>
#include <nng/supplemental/http/http.h>

int nng_http_client_set_tls(nng_http_client *client, nng_tls_config *cfg);
-----------


== DESCRIPTION

The `nng_http_client_set_tls()` sets the TLS configuration of _client_ to
_cfg_.

This change overwrites any previous TLS configuration.

WARNING: This also invalidates any previously obtained values from
<<nng_http_client_get_tls#,nng_http_client_get_tls(3)>>.

NOTE: Any connections established with
<<nng_http_client_connect#,nng_http_client_connect(3)>>
will continue to use any TLS configuration that they were started with.

== RETURN VALUES

This function returns 0 on success, and non-zero otherwise.

== ERRORS

`NNG_ENOMEM`:: Insufficient free memory exists.
`NNG_ENOTSUP`:: Either HTTP or TLS not supported.

== SEE ALSO

<<nng_http_client_alloc#,nng_http_client_alloc(3)>>,
<<nng_http_client_connect#,nng_http_client_connect(3)>>,
<<nng_http_client_get_tls#,nng_http_client_get_tls(3)>>,
<<nng_tls_config_alloc#,nng_tls_config_alloc(3)>>,
<<nng_strerror#,nng_strerror(3)>>,
<<nng#,nng(7)>>

== COPYRIGHT

{copyright}
