= nng_http_req_get_method(3)
:doctype: manpage
:manmanual: nng
:mansource: nng
:manvolnum: 3
:copyright: Copyright 2018 Staysail Systems, Inc. <info@staysail.tech> \
            Copyright 2018 Capitar IT Group BV <info@capitar.com> \
            This software is supplied under the terms of the MIT License, a \
            copy of which should be located in the distribution where this \
            file was obtained (LICENSE.txt).  A copy of the license may also \
            be found online at https://opensource.org/licenses/MIT.

== NAME

nng_http_req_get_uri - return HTTP request URI

== SYNOPSIS

[source, c]
-----------
#include <nng/nng.h>

const char *nng_http_req_get_method(nng_http_req *req);
-----------

== DESCRIPTION

The `nng_http_req_get_uri()` returns the URI (path) associated with the HTTP
the request _req_.  The value returned includes the path, as well as any
query information or fragment.  The value will look like a filesystem path
with those optional components appened, such as `/api/get_info.cgi?name=garrett`.

== RETURN VALUES

Request URI as a string.

== ERRORS

None.

== SEE ALSO

<<nng_http_req_alloc#,nng_http_req_alloc(3)>>,
<<nng_http_req_set_uri#,nng_http_req_set_uri(3)>>,
<<nng#,nng(7)>>


== COPYRIGHT

Copyright 2018 mailto:info@staysail.tech[Staysail Systems, Inc.] +
Copyright 2018 mailto:info@capitar.com[Capitar IT Group BV]

This document is supplied under the terms of the
https://opensource.org/licenses/MIT[MIT License].
