= nng_strerror(3)
:copyright: Copyright 2018 mailto:info@staysail.tech[Staysail Systems, Inc.] + \
            Copyright 2018 mailto:info@capitar.com[Capitar IT Group BV] + \
            {blank} + \
            This document is supplied under the terms of the \
            https://opensource.org/licenses/MIT[MIT License].

== NAME

nng_strerror - return an error description

== SYNOPSIS

[source, c]
-----------
#include <nng/nng.h>

const char * nng_strerror(int err);
-----------

== DESCRIPTION

The `nng_strerror()` returns the human-readable description of the
given _nng_ error in `err`.

NOTE: The returned error message is provided in US English, but in the
future locale-specific strings may be presented instead.

NOTE: The specific strings associated with specific error messages are
subject to change.  Therefore applications must not depend on the message,
but may use them verbatim when supplying information to end-users, such
as in diagnostic messages or log entries.

== RETURN VALUES

This function returns the human-readable error message, terminated
by a `NUL` byte.

== SEE ALSO

<<libnng#,libnng(3)>>,
<<nng#,nng(7)>>

== COPYRIGHT

{copyright}
