= nng_url_clone(3)
:doctype: manpage
:manmanual: nng
:mansource: nng
:manvolnum: 3
:copyright: Copyright 2018 Staysail Systems, Inc. <info@staysail.tech> \
            Copyright 2018 Capitar IT Group BV <info@capitar.com> \
            This software is supplied under the terms of the MIT License, a \
            copy of which should be located in the distribution where this \
            file was obtained (LICENSE.txt).  A copy of the license may also \
            be found online at https://opensource.org/licenses/MIT.

== NAME

nng_url_clone - clone URL structure

== SYNOPSIS

[source, c]
-----------
#include <nng/nng.h>

int nng_url_clone(nng_url **dup, nng_url *orig);
-----------

== DESCRIPTION

The `nng_url_clone()` makes a clone of the original URL structure _orig_, and
saves the result in the location pointed by _dup_.  This clone includes
fully duplicating each of the member fields.

== RETURN VALUES

This function returns 0 on success, and non-zero otherwise.

== ERRORS

`NNG_ENOMEM`:: Insufficient free memory exists to duplicate a message.

== SEE ALSO

<<nng_url_free#,nng_url_free(3)>>,
<<nng_url_parse#,nng_url_parse(3)>>,
<<nng_strerror#,nng_strerror(3)>>,
<<nng#,nng(7)>>

== COPYRIGHT

Copyright 2018 mailto:info@staysail.tech[Staysail Systems, Inc.] +
Copyright 2018 mailto:info@capitar.com[Capitar IT Group BV]

This document is supplied under the terms of the
https://opensource.org/licenses/MIT[MIT License].
