= nng_http_server_add_handler(3)
:copyright: Copyright 2018 mailto:info@staysail.tech[Staysail Systems, Inc.] + \
            Copyright 2018 mailto:info@capitar.com[Capitar IT Group BV] + \
            {blank} + \
            This document is supplied under the terms of the \
            https://opensource.org/licenses/MIT[MIT License].

== NAME

nng_http_server_add_handler - add HTTP server handler

== SYNOPSIS

[source, c]
-----------
#include <nng/nng.h>
#include <nng/supplemental/http/http.h>

int nng_http_server_add_handler(nng_http_server *s, nng_http_handler *h);
-----------


== DESCRIPTION

The `nng_http_server_add_handler()` adds the handler _h_ to the server
instance _s_.

If another handler is already added to the server that would conflict
with handler _h_, then the operation will fail with `NNG_EADDRINUSE`.

If a handler is added to a server, and the server is subsequently
deallocated, the handler and any of its resources will also be deallocated.

Handlers that are added to a server may be subsequently removed using the
<<nng_http_server_del_handler#,nng_http_server_del_handler(3)>> function.

== RETURN VALUES

This function returns 0 on success, and non-zero otherwise.

== ERRORS

`NNG_EADDRINUSE`:: Handler conflicts with another handler.
`NNG_ENOMEM`:: Insufficient free memory exists.
`NNG_ENOTSUP`:: HTTP not supported.

== SEE ALSO


<<nng_http_handler_alloc#,nng_http_handler_alloc(3)>>,
<<nng_http_server_del_handler#,nng_http_server_del_handler(3)>>,
<<nng_http_server_hold#,nng_http_server_hold(3)>>,
<<nng_strerror#,nng_strerror(3)>>,
<<nng#,nng(7)>>

== COPYRIGHT

{copyright}
