= nng_aio_stop(3)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_aio_stop - stop asynchronous I/O operation

== SYNOPSIS

[source, c]
-----------
#include <nng/nng.h>

void nng_aio_stop(nng_aio *aio);
-----------

== DESCRIPTION

The `nng_aio_stop()` function stops the asynchronous I/O operation
associated with _aio_ by aborting with `NNG_ECANCELED`, and then waits
for it to complete or to be completely aborted.

This is logically the equivalent of <<nng_aio_cancel#,nng_aio_cancel(3)>>
followed by <<nng_aio_wait#,nng_aio_wait(3)>>, except that the asynchronous
I/O handle may not be used for any further operations.

TIP: When multiple asynchronous I/O handles are in use and need to be
shut down, it is safest to stop all of them, before deallocating any of
this with <<nng_aio_free#,nng_aio_free(3)>>, particularly if the callbacks
might attempt to reschedule additional operations.

== RETURN VALUES

None.

== ERRORS

None.

== SEE ALSO

<<nng_aio_cancel#,nng_aio_cancel(3)>>,
<<nng_aio_free#,nng_aio_free(3)>>,
<<nng_aio_wait#,nng_aio_wait(3)>>,
<<nng_aio_alloc#,nng_aio_alloc(3)>>,
<<nng#,nng(7)>>
