= nng_listen(3)
:doctype: manpage
:manmanual: nng
:mansource: nng
:manvolnum: 3
:copyright: Copyright 2018 mailto:info@staysail.tech[Staysail Systems, Inc.] + \
            Copyright 2018 mailto:info@capitar.com[Capitar IT Group BV] + \
            {blank} + \
            This document is supplied under the terms of the \
            https://opensource.org/licenses/MIT[MIT License].

== NAME

nng_listen - create and start listener

== SYNOPSIS

[source, c]
-----------
#include <nng/nng.h>

int nng_listen(nng_socket s, const char *url, nng_listener *lp, int flags);
-----------

== DESCRIPTION

The `nng_listener()` function creates a newly initialized
listener, associated with socket _s_, and configured to listen at the
address specified by _url_.  If the value of _lp_ is not `NULL`, then
the newly created listener is stored at the address indicated by _lp_.

Listeners are used to accept connections initiated by remote dialers.  An
incoming connection generally results in a pipe being created and attached
to the socket _s_.  Unlike dialers, listeners generally can create many
pipes, which may be open concurrently.

TIP: While it is convenient to think of listeners as "servers", the relationship
between the listener or dialer is orthogonal to any server or client status
that might be associated with a given protocol.  For example, a <<nng_req#,REQ>>
socket might have associated dialers, but might also have associated listeners.
It may even have some of each at the same time!

Normally, the act of "binding" to the address indicated by _url_ is done
synchronously, including any necessary name resolution.  As a result,
a failure, such as if the address is already in use, will be returned
immediately.  However, if the special value `NNG_FLAG_NONBLOCK` is
supplied in _flags_, then this is done asynchronously; furthermore any
failure to bind will be periodically reattempted in the background.

TIP: While `NNG_FLAG_NONBLOCK` can help an application be more resilient,
it also generally makes diagnosing failures somewhat more difficult.

Because the listener is started immediately, it is generally not possible
to apply extra configuration; if that is needed applications should consider
using <<nng_listener_create#,nng_listener_create(3)>> and 
<<nng_listener_start#,nng_listener_start(3)>> instead.

The created listener will continue to accept new connections, associating
their pipes with the socket, until either it or the socket _s_ is closed.

== RETURN VALUES

This function returns 0 on success, and non-zero otherwise.

== ERRORS

`NNG_EADDRINUSE`:: The address specified by _url_ is already in use.
`NNG_EADDRINVAL`:: An invalid _url_ was specified.
`NNG_ECLOSED`:: The socket _s_ is not open.
`NNG_EINVAL`:: An invalid set of _flags_ was specified.
`NNG_ENOMEM`:: Insufficient memory is available.

== SEE ALSO

<<nng_strerror#,nng_strerror(3)>>,
<<nng_dial#,nng_dial(3)>>,
<<nng_listener_close#,nng_listener_close(3)>>,
<<nng_listener_create#,nng_listener_create(3)>>
<<nng_listener_start#,nng_listener_start(3)>>,
<<nng#,nng(7)>>

== COPYRIGHT

{copyright}
