= nng_aio_finish(3)
:copyright: Copyright 2018 mailto:info@staysail.tech[Staysail Systems, Inc.] + \
            Copyright 2018 mailto:info@capitar.com[Capitar IT Group BV] + \
            {blank} + \
            This document is supplied under the terms of the \
            https://opensource.org/licenses/MIT[MIT License].

== NAME

nng_aio_finish - finish asynchronous I/O operation

== SYNOPSIS

[source, c]
-----------
#include <nng/nng.h>

void nng_aio_finish(nng_aio *aio, int err);
-----------


== DESCRIPTION

The `nng_aio_finish()` function marks operation associated with _aio_ as
complete, with the status _err_.  This will be the result returned by
<<nng_aio_result#,nng_aio_result(3)>>.

This function causes the callback associated with the _aio_ to called.

WARNING: It is mandatory that operation "providers" call this function
*EXACTLY ONCE* when they are finished with the operation.  After calling this
function they *MUST NOT* perform any further accesses the _aio_.

WARNING: This function is only for I/O providers (those actually performing
the operation such as HTTP handler function or a transport provider); ordinary
users of the _aio_ should not have any need for this function.

== RETURN VALUES

None.

== ERRORS

None.

== SEE ALSO

<<nng_aio_alloc#,nng_aio_alloc(3)>>,
<<nng_aio_cancel#,nng_aio_cancel(3)>>,
<<nng_aio_result#,nng_aio_result(3)>>,
<<nng#,nng(7)>>

== COPYRIGHT

{copyright}
