= nng_aio_cancel(3)
:doctype: manpage
:manmanual: nng
:mansource: nng
:manvolnum: 3
:copyright: Copyright 2018 mailto:info@staysail.tech[Staysail Systems, Inc.] + \
            Copyright 2018 mailto:info@capitar.com[Capitar IT Group BV] + \
            {blank} + \
            This document is supplied under the terms of the \
            https://opensource.org/licenses/MIT[MIT License].

== NAME

nng_aio_cancel - cancel asynchronous I/O operation

== SYNOPSIS

[source, c]
-----------
#include <nng/nng.h>

void nng_aio_cancel(nng_aio *aio);
-----------


== DESCRIPTION

The `nng_aio_cancel()` function aborts an operation previously started
with the handle _aio_.  If the operation is aborted, then the callback
for the handle will be called, and the function
<<nng_aio_result#,nng_aio_result(3)>> will return the error `NNG_ECANCELED`.

This function does not wait for the operation to be fully aborted, but
returns immediately.

If no operation is currently in progress (either because it has already
finished, or no operation has been started yet), then this function
has no effect.

NOTE: This function is the same as calling <<nng_aio_abort#,nng_aio_abort()>>
with the error `NNG_ECANCELED`.

== RETURN VALUES

None.

== ERRORS

None.

== SEE ALSO

<<nng_aio_abort#,nng_aio_abort(3)>>,
<<nng_aio_alloc#,nng_aio_alloc(3)>>,
<<nng_aio_result#,nng_aio_result(3)>>,
<<nng#,nng(7)>>

== COPYRIGHT

{copyright}
