= nn_send(3compat)
//
// Copyright 2018 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nn_send - send data (compatible API)

== SYNOPSIS

[source, c]
----
#include <nanomsg/nn.h>

int nn_send(int sock, const void *data, size_t size, int flags)
----

== DESCRIPTION

The `nn_send()` function creates a message containing _data_ (of size _size_),
and sends using the socket _sock_.

NOTE: This function is provided for API
xref:nng_compat.3compat.adoc[compatibility] with legacy _libnanomsg_.
Consider using the relevant xref:libnng.3.adoc[modern API] instead.

If _size_ has the special value `NN_MSG`, then a zero-copy operation
is performed.
In this case, _data_ points not to the message content itself, but instead
is a pointer to the pointer, an extra level of pointer indirection.
The message must have been previously allocated by
xref:nn_allocmsg.3compat.adoc[`nn_allocmsg()`] or
xref:nn_recvmsg.3compat.adoc[`nn_recvmsg()`]`, using the same `NN_MSG` size.
In this case, the ownership of the message shall remain with
the caller, unless the function returns 0, indicating that the
function has taken responsibility for delivering or disposing of the
message.

The _flags_ field may contain the special flag `NN_DONTWAIT`.
In this case, if the socket is unable to accept more data for sending,
the operation shall not block, but instead will fail with the error `EAGAIN`.

NOTE: The send operation is performed asynchronously, and may not have
completed before this function returns control to the caller.

== RETURN VALUES

This function returns the number of bytes sent on success, and -1 on error.

== ERRORS

[horizontal]
`EAGAIN`:: The operation would block.
`EBADF`:: The socket _sock_ is not open.
`EFSM`:: The socket cannot send in this state.
`ENOTSUP`:: This protocol cannot send.
`ETIMEDOUT`:: Operation timed out.

== SEE ALSO

[.text-left]
xref:nn_errno.3compat.adoc[nn_errno(3compat)],
xref:nn_recv.3compat.adoc[nn_recv(3compat)],
xref:nn_sendmsg.3compat.adoc[nn_sendmsg(3compat)],
xref:nn_socket.3compat.adoc[nn_socket(3compat)],
xref:nng_compat.3compat.adoc[nn_compat(3compat)],
xref:nng.7.adoc[nng(7)]
