= nn_shutdown(3compat)
//
// Copyright 2020 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nn_shutdown - shut down endpoint (compatible API)

== SYNOPSIS

[source, c]
----
#include <nanomsg/nn.h>

int nn_shutdown(int sock, int ep)
----

== DESCRIPTION

The `nn_shutdown()` shuts down the endpoint _ep_, which is either a listener or
a dialer) on the socket _sock_.
This will stop the socket from either accepting new connections, or establishing
old ones.
Additionally, any established connections associated with _ep_ will be closed.

NOTE: This function is provided for API
xref:nng_compat.3compat.adoc[compatibility] with legacy _libnanomsg_.
Consider using the relevant xref:libnng.3.adoc[modern API] instead.

== RETURN VALUES

This function returns zero on success, and -1 on error.

== ERRORS

[horizontal]
`EBADF`:: The socket _sock_ is not open.
`EINVAL`:: An invalid _ep_ was supplied.

== SEE ALSO

[.text-left]
xref:nn_bind.3compat.adoc[nn_bind(3compat)],
xref:nn_connect.3compat.adoc[nn_connect(3compat)],
xref:nn_errno.3compat.adoc[nn_errno(3compat)],
xref:nn_socket.3compat.adoc[nn_socket(3compat)],
xref:nng_compat.3compat.adoc[nn_compat(3compat)],
xref:nng.7.adoc[nng(7)]
