name: darwin
on: [push]
jobs:

  build:
    name: build
    runs-on: [ macos-latest ]
    steps:
    - name: Check out code
      uses: actions/checkout@v1

    - name: Install ninja
      run: brew install ninja

    - name: Configure
      run: mkdir build && cd build && cmake -G Ninja ..

    - name: build
      run: cd build && ninja

    - name: Test
      run: cd build && ctest --output-on-failure