= nng_stream_recv(3str)
//
// Copyright 2019 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
// Copyright 2019 Devolutions <info@devolutions.net>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_stream_recv - receive from byte stream

== SYNOPSIS

[source, c]
----
#include <nng/nng.h>

void nng_stream_recv(nng_stream *s, nng_aio *aio);
----

== DESCRIPTION

The `nng_stream_recv()` function starts an asynchronous receive from the
xref:nng_stream.5.adoc[byte stream] _s_
into the scatter/gather vector located in the
asynchronous I/O structure _aio_.

NOTE: The
xref:nng_aio_set_iov.3.adoc[`nng_aio_set_iov()`] function must have been
called first, to set the scatter/gather vector for _aio_.

This function returns immediately, with no return value.
Completion of the operation is signaled via the _aio_,
and the final result may be obtained via
xref:nng_aio_result.3.adoc[`nng_aio_result()`].
That result will either be zero or an error code.

The I/O operation completes as soon as at least one byte has been
received, or an error has occurred.
Therefore, the number of bytes read may be less than requested.
The actual number of bytes read can be determined with
xref:nng_aio_count.3.adoc[`nng_aio_count()`].

== RETURN VALUES

None.

== ERRORS

[horizontal]
`NNG_ECANCELED`:: The operation was canceled.
`NNG_ECLOSED`:: The connection was closed.
`NNG_ECONNRESET`:: The peer closed the connection.
`NNG_ECONNSHUT`:: Remote peer shutdown after sending data.
`NNG_EINVAL`:: The _aio_ does not contain a valid scatter/gather vector.
`NNG_ENOMEM`:: Insufficient free memory to perform the operation.
`NNG_ETIMEDOUT`:: Timeout waiting for data from the connection.

== SEE ALSO

[.text-left]
xref:nng_aio_alloc.3.adoc[nng_aio_alloc(3)],
xref:nng_aio_count.3.adoc[nng_aio_count(3)],
xref:nng_aio_result.3.adoc[nng_aio_result(3)],
xref:nng_aio_set_iov.3.adoc[nng_aio_set_iov(3)],
xref:nng_strerror.3.adoc[nng_strerror(3)],
xref:nng_stream_close.3str.adoc[nng_stream_close(3str)],
xref:nng_stream_send.3str.adoc[nng_stream_send(3str)],
xref:nng_stream.5.adoc[nng_stream(5)]
